<?php /* Smarty version 2.6.26, created on 2011-11-22 17:44:33
         compiled from ./core/main.tpl */ ?>
﻿<?php echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title>AdressBooX: '; ?><?php echo $this->_tpl_vars['title']; ?><?php echo '</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="expires" content="0"><meta name="language" content="de"><meta name="author" content="'; ?><?php echo $this->_tpl_vars['_website_autor']; ?><?php echo '"><meta name="generator" content="Notepad++"><meta name="description" content="TypeChef WebInterface"><meta name="keywords" content="TypeChef WebInterface,TypeChef,WebInterface,TypeChefWebInt"><meta name="robots" content="all"><link rel="stylesheet" type="text/css" href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/stylesheets/main.css"><link rel="stylesheet" type="text/css" href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/stylesheets/form.css"><link rel="stylesheet" type="text/css" href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/stylesheets/table.css"><link rel="stylesheet" type="text/css" href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/stylesheets/links.css"><link rel="shortcut icon" type="image/ico" href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/icons/favicon.ico"/><!--[if lt IE 7.]><script defer type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/include/javascripts/pngfix/pngfix.js"></script><![endif]--></head><body class="body"><table align="left" border="1" cellpadding="0" cellspacing="0"><colgroup><col width="400"><col width="600"></colgroup><tr><td align="center" colspan="2">TypeChef - WebInterface</td></tr><tr><th rowspan="2">'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "./core/tree.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</th><td><a href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/" class="link">Startseite</a> - <a href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/501_not_implemented" class="link">Ein Menüpunkt</a> - <a href="'; ?><?php echo $this->_tpl_vars['_wud']; ?><?php echo '/501_not_implemented" class="link">Einstellungen</a></td></tr><tr><td>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['template'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</td></tr><tr><td align="center" colspan="2"><br><div style="font-family:verdana; font-size:12px; color:black; padding-top:5px;">(c) '; ?><?php echo $this->_tpl_vars['_website_year']; ?><?php echo ' by '; ?><?php echo $this->_tpl_vars['_website_autor']; ?><?php echo '<br><br>Version '; ?><?php echo $this->_tpl_vars['_website_version']; ?><?php echo '</div></td></tr></table></body></html>'; ?>
