	DRIVER_DIR=./linux

w35und-objs := linux/wbusb.o linux/wb35reg.o linux/wb35rx.o linux/wb35tx.o \
	mds.o \
	mlmetxrx.o \
	mto.o	\
	phy_calibration.o	\
	reg.o			\
	rxisr.o			\
	sme_api.o		\
	wbhal.o			\
	wblinux.o		\


obj-$(CONFIG_W35UND) += w35und.o



