USETEXTLINKS = 1
STARTALLOPEN = 0
ICONPATH = '/~eifx/TypeChefWebInt/php/include/images/treeview/'
foldersTree = gFld("<i>busybox</i>", "")
foldersTree.treeID = "Frameset"
foldersTree.iconSrc = ICONPATH + "folderopenfail.gif"
foldersTree.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
applets = insFld(foldersTree, gFld("applets", ""))
applets.iconSrc = ICONPATH + "folderopenok.gif"
applets.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc0 = insDoc(applets, gLnk("S", "applets - Copy.dbg", "noLinkInserted"))
doc0.iconSrc = ICONPATH + "fileok.gif"
doc1 = insDoc(applets, gLnk("S", "applets.dbg", "noLinkInserted"))
doc1.iconSrc = ICONPATH + "fileok.gif"
archival = insFld(foldersTree, gFld("archival", ""))
archival.iconSrc = ICONPATH + "folderopenok.gif"
archival.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc2 = insDoc(archival, gLnk("S", "ar.dbg", "noLinkInserted"))
doc2.iconSrc = ICONPATH + "fileok.gif"
doc3 = insDoc(archival, gLnk("S", "bbunzip.dbg", "noLinkInserted"))
doc3.iconSrc = ICONPATH + "fileok.gif"
doc4 = insDoc(archival, gLnk("S", "bzip2.dbg", "noLinkInserted"))
doc4.iconSrc = ICONPATH + "fileok.gif"
doc5 = insDoc(archival, gLnk("S", "cpio.dbg", "noLinkInserted"))
doc5.iconSrc = ICONPATH + "fileok.gif"
doc6 = insDoc(archival, gLnk("S", "dpkg.dbg", "noLinkInserted"))
doc6.iconSrc = ICONPATH + "fileok.gif"
doc7 = insDoc(archival, gLnk("S", "dpkg_deb.dbg", "noLinkInserted"))
doc7.iconSrc = ICONPATH + "fileok.gif"
doc8 = insDoc(archival, gLnk("S", "gzip.dbg", "noLinkInserted"))
doc8.iconSrc = ICONPATH + "fileok.gif"
libarchive = insFld(archival, gFld("libarchive", ""))
libarchive.iconSrc = ICONPATH + "folderopenok.gif"
libarchive.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc9 = insDoc(libarchive, gLnk("S", "data_align.dbg", "noLinkInserted"))
doc9.iconSrc = ICONPATH + "fileok.gif"
doc10 = insDoc(libarchive, gLnk("S", "data_extract_all.dbg", "noLinkInserted"))
doc10.iconSrc = ICONPATH + "fileok.gif"
doc11 = insDoc(libarchive, gLnk("S", "data_extract_to_command.dbg", "noLinkInserted"))
doc11.iconSrc = ICONPATH + "fileok.gif"
doc12 = insDoc(libarchive, gLnk("S", "data_extract_to_stdout.dbg", "noLinkInserted"))
doc12.iconSrc = ICONPATH + "fileok.gif"
doc13 = insDoc(libarchive, gLnk("S", "data_skip.dbg", "noLinkInserted"))
doc13.iconSrc = ICONPATH + "fileok.gif"
doc14 = insDoc(libarchive, gLnk("S", "decompress_bunzip2.dbg", "noLinkInserted"))
doc14.iconSrc = ICONPATH + "fileok.gif"
doc15 = insDoc(libarchive, gLnk("S", "decompress_uncompress.dbg", "noLinkInserted"))
doc15.iconSrc = ICONPATH + "fileok.gif"
doc16 = insDoc(libarchive, gLnk("S", "decompress_unlzma.dbg", "noLinkInserted"))
doc16.iconSrc = ICONPATH + "fileok.gif"
doc17 = insDoc(libarchive, gLnk("S", "decompress_unxz.dbg", "noLinkInserted"))
doc17.iconSrc = ICONPATH + "fileok.gif"
doc18 = insDoc(libarchive, gLnk("S", "decompress_unzip.dbg", "noLinkInserted"))
doc18.iconSrc = ICONPATH + "fileok.gif"
doc19 = insDoc(libarchive, gLnk("S", "filter_accept_all.dbg", "noLinkInserted"))
doc19.iconSrc = ICONPATH + "fileok.gif"
doc20 = insDoc(libarchive, gLnk("S", "filter_accept_list.dbg", "noLinkInserted"))
doc20.iconSrc = ICONPATH + "fileok.gif"
doc21 = insDoc(libarchive, gLnk("S", "filter_accept_list_reassign.dbg", "noLinkInserted"))
doc21.iconSrc = ICONPATH + "fileok.gif"
doc22 = insDoc(libarchive, gLnk("S", "filter_accept_reject_list.dbg", "noLinkInserted"))
doc22.iconSrc = ICONPATH + "fileok.gif"
doc23 = insDoc(libarchive, gLnk("S", "find_list_entry.dbg", "noLinkInserted"))
doc23.iconSrc = ICONPATH + "fileok.gif"
doc24 = insDoc(libarchive, gLnk("S", "get_header_ar.dbg", "noLinkInserted"))
doc24.iconSrc = ICONPATH + "fileok.gif"
doc25 = insDoc(libarchive, gLnk("S", "get_header_cpio.dbg", "noLinkInserted"))
doc25.iconSrc = ICONPATH + "fileok.gif"
doc26 = insDoc(libarchive, gLnk("S", "get_header_tar.dbg", "noLinkInserted"))
doc26.iconSrc = ICONPATH + "fileok.gif"
doc27 = insDoc(libarchive, gLnk("S", "get_header_tar_bz2.dbg", "noLinkInserted"))
doc27.iconSrc = ICONPATH + "fileok.gif"
doc28 = insDoc(libarchive, gLnk("S", "get_header_tar_gz.dbg", "noLinkInserted"))
doc28.iconSrc = ICONPATH + "fileok.gif"
doc29 = insDoc(libarchive, gLnk("S", "get_header_tar_lzma.dbg", "noLinkInserted"))
doc29.iconSrc = ICONPATH + "fileok.gif"
doc30 = insDoc(libarchive, gLnk("S", "header_list.dbg", "noLinkInserted"))
doc30.iconSrc = ICONPATH + "fileok.gif"
doc31 = insDoc(libarchive, gLnk("S", "header_skip.dbg", "noLinkInserted"))
doc31.iconSrc = ICONPATH + "fileok.gif"
doc32 = insDoc(libarchive, gLnk("S", "header_verbose_list.dbg", "noLinkInserted"))
doc32.iconSrc = ICONPATH + "fileok.gif"
doc33 = insDoc(libarchive, gLnk("S", "init_handle.dbg", "noLinkInserted"))
doc33.iconSrc = ICONPATH + "fileok.gif"
doc34 = insDoc(libarchive, gLnk("S", "lzo1x_1.dbg", "noLinkInserted"))
doc34.iconSrc = ICONPATH + "fileok.gif"
doc35 = insDoc(libarchive, gLnk("S", "lzo1x_1o.dbg", "noLinkInserted"))
doc35.iconSrc = ICONPATH + "fileok.gif"
doc36 = insDoc(libarchive, gLnk("S", "lzo1x_9x.dbg", "noLinkInserted"))
doc36.iconSrc = ICONPATH + "fileok.gif"
doc37 = insDoc(libarchive, gLnk("S", "lzo1x_d.dbg", "noLinkInserted"))
doc37.iconSrc = ICONPATH + "fileok.gif"
doc38 = insDoc(libarchive, gLnk("S", "open_transformer.dbg", "noLinkInserted"))
doc38.iconSrc = ICONPATH + "fileok.gif"
doc39 = insDoc(libarchive, gLnk("S", "seek_by_jump.dbg", "noLinkInserted"))
doc39.iconSrc = ICONPATH + "fileok.gif"
doc40 = insDoc(libarchive, gLnk("S", "seek_by_read.dbg", "noLinkInserted"))
doc40.iconSrc = ICONPATH + "fileok.gif"
doc41 = insDoc(libarchive, gLnk("S", "unpack_ar_archive.dbg", "noLinkInserted"))
doc41.iconSrc = ICONPATH + "fileok.gif"
doc42 = insDoc(archival, gLnk("S", "lzop.dbg", "noLinkInserted"))
doc42.iconSrc = ICONPATH + "fileok.gif"
doc43 = insDoc(archival, gLnk("S", "rpm.dbg", "noLinkInserted"))
doc43.iconSrc = ICONPATH + "fileok.gif"
doc44 = insDoc(archival, gLnk("S", "rpm2cpio.dbg", "noLinkInserted"))
doc44.iconSrc = ICONPATH + "fileok.gif"
doc45 = insDoc(archival, gLnk("S", "tar.dbg", "noLinkInserted"))
doc45.iconSrc = ICONPATH + "fileok.gif"
doc46 = insDoc(archival, gLnk("S", "unzip.dbg", "noLinkInserted"))
doc46.iconSrc = ICONPATH + "fileok.gif"
console_tools = insFld(foldersTree, gFld("console-tools", ""))
console_tools.iconSrc = ICONPATH + "folderopenok.gif"
console_tools.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc47 = insDoc(console_tools, gLnk("S", "chvt.dbg", "noLinkInserted"))
doc47.iconSrc = ICONPATH + "fileok.gif"
doc48 = insDoc(console_tools, gLnk("S", "clear.dbg", "noLinkInserted"))
doc48.iconSrc = ICONPATH + "fileok.gif"
doc49 = insDoc(console_tools, gLnk("S", "deallocvt.dbg", "noLinkInserted"))
doc49.iconSrc = ICONPATH + "fileok.gif"
doc50 = insDoc(console_tools, gLnk("S", "dumpkmap.dbg", "noLinkInserted"))
doc50.iconSrc = ICONPATH + "fileok.gif"
doc51 = insDoc(console_tools, gLnk("S", "fgconsole.dbg", "noLinkInserted"))
doc51.iconSrc = ICONPATH + "fileok.gif"
doc52 = insDoc(console_tools, gLnk("S", "kbd_mode.dbg", "noLinkInserted"))
doc52.iconSrc = ICONPATH + "fileok.gif"
doc53 = insDoc(console_tools, gLnk("S", "loadfont.dbg", "noLinkInserted"))
doc53.iconSrc = ICONPATH + "fileok.gif"
doc54 = insDoc(console_tools, gLnk("S", "loadkmap.dbg", "noLinkInserted"))
doc54.iconSrc = ICONPATH + "fileok.gif"
doc55 = insDoc(console_tools, gLnk("S", "openvt.dbg", "noLinkInserted"))
doc55.iconSrc = ICONPATH + "fileok.gif"
doc56 = insDoc(console_tools, gLnk("S", "reset.dbg", "noLinkInserted"))
doc56.iconSrc = ICONPATH + "fileok.gif"
doc57 = insDoc(console_tools, gLnk("S", "resize.dbg", "noLinkInserted"))
doc57.iconSrc = ICONPATH + "fileok.gif"
doc58 = insDoc(console_tools, gLnk("S", "setconsole.dbg", "noLinkInserted"))
doc58.iconSrc = ICONPATH + "fileok.gif"
doc59 = insDoc(console_tools, gLnk("S", "setkeycodes.dbg", "noLinkInserted"))
doc59.iconSrc = ICONPATH + "fileok.gif"
doc60 = insDoc(console_tools, gLnk("S", "setlogcons.dbg", "noLinkInserted"))
doc60.iconSrc = ICONPATH + "fileok.gif"
doc61 = insDoc(console_tools, gLnk("S", "showkey.dbg", "noLinkInserted"))
doc61.iconSrc = ICONPATH + "fileok.gif"
coreutils = insFld(foldersTree, gFld("coreutils", ""))
coreutils.iconSrc = ICONPATH + "folderopenfail.gif"
coreutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc62 = insDoc(coreutils, gLnk("S", "basename.dbg", "noLinkInserted"))
doc62.iconSrc = ICONPATH + "fileok.gif"
doc63 = insDoc(coreutils, gLnk("S", "cal.dbg", "noLinkInserted"))
doc63.iconSrc = ICONPATH + "fileok.gif"
doc64 = insDoc(coreutils, gLnk("S", "cat.dbg", "noLinkInserted"))
doc64.iconSrc = ICONPATH + "fileok.gif"
doc65 = insDoc(coreutils, gLnk("S", "catv.dbg", "noLinkInserted"))
doc65.iconSrc = ICONPATH + "fileok.gif"
doc66 = insDoc(coreutils, gLnk("S", "chgrp.dbg", "noLinkInserted"))
doc66.iconSrc = ICONPATH + "fileok.gif"
doc67 = insDoc(coreutils, gLnk("S", "chmod.dbg", "noLinkInserted"))
doc67.iconSrc = ICONPATH + "fileok.gif"
doc68 = insDoc(coreutils, gLnk("S", "chown.dbg", "noLinkInserted"))
doc68.iconSrc = ICONPATH + "fileok.gif"
doc69 = insDoc(coreutils, gLnk("S", "chroot.dbg", "noLinkInserted"))
doc69.iconSrc = ICONPATH + "fileok.gif"
doc70 = insDoc(coreutils, gLnk("S", "cksum.dbg", "noLinkInserted"))
doc70.iconSrc = ICONPATH + "fileok.gif"
doc71 = insDoc(coreutils, gLnk("S", "comm.dbg", "noLinkInserted"))
doc71.iconSrc = ICONPATH + "fileok.gif"
doc72 = insDoc(coreutils, gLnk("S", "cp.dbg", "noLinkInserted"))
doc72.iconSrc = ICONPATH + "fileok.gif"
doc73 = insDoc(coreutils, gLnk("S", "cut.dbg", "noLinkInserted"))
doc73.iconSrc = ICONPATH + "fileok.gif"
doc74 = insDoc(coreutils, gLnk("S", "date.dbg", "noLinkInserted"))
doc74.iconSrc = ICONPATH + "filefail.gif"
doc75 = insDoc(coreutils, gLnk("S", "dd.dbg", "noLinkInserted"))
doc75.iconSrc = ICONPATH + "fileok.gif"
doc76 = insDoc(coreutils, gLnk("S", "df.dbg", "noLinkInserted"))
doc76.iconSrc = ICONPATH + "fileok.gif"
doc77 = insDoc(coreutils, gLnk("S", "dirname.dbg", "noLinkInserted"))
doc77.iconSrc = ICONPATH + "fileok.gif"
doc78 = insDoc(coreutils, gLnk("S", "dos2unix.dbg", "noLinkInserted"))
doc78.iconSrc = ICONPATH + "fileok.gif"
doc79 = insDoc(coreutils, gLnk("S", "du.dbg", "noLinkInserted"))
doc79.iconSrc = ICONPATH + "fileok.gif"
doc80 = insDoc(coreutils, gLnk("S", "echo.dbg", "noLinkInserted"))
doc80.iconSrc = ICONPATH + "fileok.gif"
doc81 = insDoc(coreutils, gLnk("S", "env.dbg", "noLinkInserted"))
doc81.iconSrc = ICONPATH + "fileok.gif"
doc82 = insDoc(coreutils, gLnk("S", "expand.dbg", "noLinkInserted"))
doc82.iconSrc = ICONPATH + "fileok.gif"
doc83 = insDoc(coreutils, gLnk("S", "expr.dbg", "noLinkInserted"))
doc83.iconSrc = ICONPATH + "fileok.gif"
doc84 = insDoc(coreutils, gLnk("S", "false.dbg", "noLinkInserted"))
doc84.iconSrc = ICONPATH + "fileok.gif"
doc85 = insDoc(coreutils, gLnk("S", "fold.dbg", "noLinkInserted"))
doc85.iconSrc = ICONPATH + "fileok.gif"
doc86 = insDoc(coreutils, gLnk("S", "fsync.dbg", "noLinkInserted"))
doc86.iconSrc = ICONPATH + "fileok.gif"
doc87 = insDoc(coreutils, gLnk("S", "head.dbg", "noLinkInserted"))
doc87.iconSrc = ICONPATH + "fileok.gif"
doc88 = insDoc(coreutils, gLnk("S", "hostid.dbg", "noLinkInserted"))
doc88.iconSrc = ICONPATH + "fileok.gif"
doc89 = insDoc(coreutils, gLnk("S", "id.dbg", "noLinkInserted"))
doc89.iconSrc = ICONPATH + "fileok.gif"
doc90 = insDoc(coreutils, gLnk("S", "install.dbg", "noLinkInserted"))
doc90.iconSrc = ICONPATH + "fileok.gif"
doc91 = insDoc(coreutils, gLnk("S", "length.dbg", "noLinkInserted"))
doc91.iconSrc = ICONPATH + "fileok.gif"
libcoreutils = insFld(coreutils, gFld("libcoreutils", ""))
libcoreutils.iconSrc = ICONPATH + "folderopenok.gif"
libcoreutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc92 = insDoc(libcoreutils, gLnk("S", "cp_mv_stat.dbg", "noLinkInserted"))
doc92.iconSrc = ICONPATH + "fileok.gif"
doc93 = insDoc(libcoreutils, gLnk("S", "getopt_mk_fifo_nod.dbg", "noLinkInserted"))
doc93.iconSrc = ICONPATH + "fileok.gif"
doc94 = insDoc(coreutils, gLnk("S", "ln.dbg", "noLinkInserted"))
doc94.iconSrc = ICONPATH + "fileok.gif"
doc95 = insDoc(coreutils, gLnk("S", "logname.dbg", "noLinkInserted"))
doc95.iconSrc = ICONPATH + "fileok.gif"
doc96 = insDoc(coreutils, gLnk("S", "ls.dbg", "noLinkInserted"))
doc96.iconSrc = ICONPATH + "fileok.gif"
doc97 = insDoc(coreutils, gLnk("S", "md5_sha1_sum.dbg", "noLinkInserted"))
doc97.iconSrc = ICONPATH + "fileok.gif"
doc98 = insDoc(coreutils, gLnk("S", "mkdir.dbg", "noLinkInserted"))
doc98.iconSrc = ICONPATH + "fileok.gif"
doc99 = insDoc(coreutils, gLnk("S", "mkfifo.dbg", "noLinkInserted"))
doc99.iconSrc = ICONPATH + "fileok.gif"
doc100 = insDoc(coreutils, gLnk("S", "mknod.dbg", "noLinkInserted"))
doc100.iconSrc = ICONPATH + "fileok.gif"
doc101 = insDoc(coreutils, gLnk("S", "mv.dbg", "noLinkInserted"))
doc101.iconSrc = ICONPATH + "fileok.gif"
doc102 = insDoc(coreutils, gLnk("S", "nice.dbg", "noLinkInserted"))
doc102.iconSrc = ICONPATH + "fileok.gif"
doc103 = insDoc(coreutils, gLnk("S", "nohup.dbg", "noLinkInserted"))
doc103.iconSrc = ICONPATH + "fileok.gif"
doc104 = insDoc(coreutils, gLnk("S", "od.dbg", "noLinkInserted"))
doc104.iconSrc = ICONPATH + "fileok.gif"
doc105 = insDoc(coreutils, gLnk("S", "printenv.dbg", "noLinkInserted"))
doc105.iconSrc = ICONPATH + "fileok.gif"
doc106 = insDoc(coreutils, gLnk("S", "printf.dbg", "noLinkInserted"))
doc106.iconSrc = ICONPATH + "fileok.gif"
doc107 = insDoc(coreutils, gLnk("S", "pwd.dbg", "noLinkInserted"))
doc107.iconSrc = ICONPATH + "fileok.gif"
doc108 = insDoc(coreutils, gLnk("S", "readlink.dbg", "noLinkInserted"))
doc108.iconSrc = ICONPATH + "fileok.gif"
doc109 = insDoc(coreutils, gLnk("S", "realpath.dbg", "noLinkInserted"))
doc109.iconSrc = ICONPATH + "fileok.gif"
doc110 = insDoc(coreutils, gLnk("S", "rm.dbg", "noLinkInserted"))
doc110.iconSrc = ICONPATH + "fileok.gif"
doc111 = insDoc(coreutils, gLnk("S", "rmdir.dbg", "noLinkInserted"))
doc111.iconSrc = ICONPATH + "fileok.gif"
doc112 = insDoc(coreutils, gLnk("S", "seq.dbg", "noLinkInserted"))
doc112.iconSrc = ICONPATH + "filefail.gif"
doc113 = insDoc(coreutils, gLnk("S", "sleep.dbg", "noLinkInserted"))
doc113.iconSrc = ICONPATH + "fileok.gif"
doc114 = insDoc(coreutils, gLnk("S", "sort.dbg", "noLinkInserted"))
doc114.iconSrc = ICONPATH + "filefail.gif"
doc115 = insDoc(coreutils, gLnk("S", "split.dbg", "noLinkInserted"))
doc115.iconSrc = ICONPATH + "fileok.gif"
doc116 = insDoc(coreutils, gLnk("S", "stat.dbg", "noLinkInserted"))
doc116.iconSrc = ICONPATH + "fileok.gif"
doc117 = insDoc(coreutils, gLnk("S", "stty.dbg", "noLinkInserted"))
doc117.iconSrc = ICONPATH + "fileok.gif"
doc118 = insDoc(coreutils, gLnk("S", "sum.dbg", "noLinkInserted"))
doc118.iconSrc = ICONPATH + "fileok.gif"
doc119 = insDoc(coreutils, gLnk("S", "sync.dbg", "noLinkInserted"))
doc119.iconSrc = ICONPATH + "fileok.gif"
doc120 = insDoc(coreutils, gLnk("S", "tac.dbg", "noLinkInserted"))
doc120.iconSrc = ICONPATH + "fileok.gif"
doc121 = insDoc(coreutils, gLnk("S", "tail.dbg", "noLinkInserted"))
doc121.iconSrc = ICONPATH + "fileok.gif"
doc122 = insDoc(coreutils, gLnk("S", "tee.dbg", "noLinkInserted"))
doc122.iconSrc = ICONPATH + "fileok.gif"
doc123 = insDoc(coreutils, gLnk("S", "test.dbg", "noLinkInserted"))
doc123.iconSrc = ICONPATH + "fileok.gif"
doc124 = insDoc(coreutils, gLnk("S", "test_ptr_hack.dbg", "noLinkInserted"))
doc124.iconSrc = ICONPATH + "fileok.gif"
doc125 = insDoc(coreutils, gLnk("S", "touch.dbg", "noLinkInserted"))
doc125.iconSrc = ICONPATH + "fileok.gif"
doc126 = insDoc(coreutils, gLnk("S", "tr.dbg", "noLinkInserted"))
doc126.iconSrc = ICONPATH + "fileok.gif"
doc127 = insDoc(coreutils, gLnk("S", "true.dbg", "noLinkInserted"))
doc127.iconSrc = ICONPATH + "fileok.gif"
doc128 = insDoc(coreutils, gLnk("S", "tty.dbg", "noLinkInserted"))
doc128.iconSrc = ICONPATH + "fileok.gif"
doc129 = insDoc(coreutils, gLnk("S", "uname.dbg", "noLinkInserted"))
doc129.iconSrc = ICONPATH + "fileok.gif"
doc130 = insDoc(coreutils, gLnk("S", "uniq.dbg", "noLinkInserted"))
doc130.iconSrc = ICONPATH + "fileok.gif"
doc131 = insDoc(coreutils, gLnk("S", "usleep.dbg", "noLinkInserted"))
doc131.iconSrc = ICONPATH + "fileok.gif"
doc132 = insDoc(coreutils, gLnk("S", "uudecode.dbg", "noLinkInserted"))
doc132.iconSrc = ICONPATH + "fileok.gif"
doc133 = insDoc(coreutils, gLnk("S", "uuencode.dbg", "noLinkInserted"))
doc133.iconSrc = ICONPATH + "fileok.gif"
doc134 = insDoc(coreutils, gLnk("S", "wc.dbg", "noLinkInserted"))
doc134.iconSrc = ICONPATH + "fileok.gif"
doc135 = insDoc(coreutils, gLnk("S", "who.dbg", "noLinkInserted"))
doc135.iconSrc = ICONPATH + "fileok.gif"
doc136 = insDoc(coreutils, gLnk("S", "whoami.dbg", "noLinkInserted"))
doc136.iconSrc = ICONPATH + "fileok.gif"
doc137 = insDoc(coreutils, gLnk("S", "yes.dbg", "noLinkInserted"))
doc137.iconSrc = ICONPATH + "fileok.gif"
debianutils = insFld(foldersTree, gFld("debianutils", ""))
debianutils.iconSrc = ICONPATH + "folderopenok.gif"
debianutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc138 = insDoc(debianutils, gLnk("S", "mktemp.dbg", "noLinkInserted"))
doc138.iconSrc = ICONPATH + "fileok.gif"
doc139 = insDoc(debianutils, gLnk("S", "pipe_progress.dbg", "noLinkInserted"))
doc139.iconSrc = ICONPATH + "fileok.gif"
doc140 = insDoc(debianutils, gLnk("S", "run_parts.dbg", "noLinkInserted"))
doc140.iconSrc = ICONPATH + "fileok.gif"
doc141 = insDoc(debianutils, gLnk("S", "start_stop_daemon.dbg", "noLinkInserted"))
doc141.iconSrc = ICONPATH + "fileok.gif"
doc142 = insDoc(debianutils, gLnk("S", "which.dbg", "noLinkInserted"))
doc142.iconSrc = ICONPATH + "fileok.gif"
e2fsprogs = insFld(foldersTree, gFld("e2fsprogs", ""))
e2fsprogs.iconSrc = ICONPATH + "folderopenok.gif"
e2fsprogs.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc143 = insDoc(e2fsprogs, gLnk("S", "chattr.dbg", "noLinkInserted"))
doc143.iconSrc = ICONPATH + "fileok.gif"
doc144 = insDoc(e2fsprogs, gLnk("S", "e2fs_lib.dbg", "noLinkInserted"))
doc144.iconSrc = ICONPATH + "fileok.gif"
doc145 = insDoc(e2fsprogs, gLnk("S", "fsck.dbg", "noLinkInserted"))
doc145.iconSrc = ICONPATH + "fileok.gif"
doc146 = insDoc(e2fsprogs, gLnk("S", "lsattr.dbg", "noLinkInserted"))
doc146.iconSrc = ICONPATH + "fileok.gif"
doc147 = insDoc(e2fsprogs, gLnk("S", "tune2fs.dbg", "noLinkInserted"))
doc147.iconSrc = ICONPATH + "fileok.gif"
editors = insFld(foldersTree, gFld("editors", ""))
editors.iconSrc = ICONPATH + "folderopenfail.gif"
editors.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc148 = insDoc(editors, gLnk("S", "awk.dbg", "noLinkInserted"))
doc148.iconSrc = ICONPATH + "fileok.gif"
doc149 = insDoc(editors, gLnk("S", "cmp.dbg", "noLinkInserted"))
doc149.iconSrc = ICONPATH + "fileok.gif"
doc150 = insDoc(editors, gLnk("S", "diff.dbg", "noLinkInserted"))
doc150.iconSrc = ICONPATH + "fileok.gif"
doc151 = insDoc(editors, gLnk("S", "ed.dbg", "noLinkInserted"))
doc151.iconSrc = ICONPATH + "fileok.gif"
doc152 = insDoc(editors, gLnk("S", "patch.dbg", "noLinkInserted"))
doc152.iconSrc = ICONPATH + "fileok.gif"
doc153 = insDoc(editors, gLnk("S", "sed.dbg", "noLinkInserted"))
doc153.iconSrc = ICONPATH + "fileok.gif"
doc154 = insDoc(editors, gLnk("S", "vi.dbg", "noLinkInserted"))
doc154.iconSrc = ICONPATH + "filefail.gif"
findutils = insFld(foldersTree, gFld("findutils", ""))
findutils.iconSrc = ICONPATH + "folderopenfail.gif"
findutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc155 = insDoc(findutils, gLnk("S", "find.dbg", "noLinkInserted"))
doc155.iconSrc = ICONPATH + "fileok.gif"
doc156 = insDoc(findutils, gLnk("S", "grep.dbg", "noLinkInserted"))
doc156.iconSrc = ICONPATH + "filefail.gif"
doc157 = insDoc(findutils, gLnk("S", "xargs.dbg", "noLinkInserted"))
doc157.iconSrc = ICONPATH + "fileok.gif"
init = insFld(foldersTree, gFld("init", ""))
init.iconSrc = ICONPATH + "folderopenfail.gif"
init.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc158 = insDoc(init, gLnk("S", "bootchartd.dbg", "noLinkInserted"))
doc158.iconSrc = ICONPATH + "filefail.gif"
doc159 = insDoc(init, gLnk("S", "halt.dbg", "noLinkInserted"))
doc159.iconSrc = ICONPATH + "fileok.gif"
doc160 = insDoc(init, gLnk("S", "init.dbg", "noLinkInserted"))
doc160.iconSrc = ICONPATH + "fileok.gif"
doc161 = insDoc(init, gLnk("S", "mesg.dbg", "noLinkInserted"))
doc161.iconSrc = ICONPATH + "fileok.gif"
libbb = insFld(foldersTree, gFld("libbb", ""))
libbb.iconSrc = ICONPATH + "folderopenfail.gif"
libbb.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc162 = insDoc(libbb, gLnk("S", "appletlib.dbg", "noLinkInserted"))
doc162.iconSrc = ICONPATH + "filefail.gif"
doc163 = insDoc(libbb, gLnk("S", "ask_confirmation.dbg", "noLinkInserted"))
doc163.iconSrc = ICONPATH + "fileok.gif"
doc164 = insDoc(libbb, gLnk("S", "bb_askpass.dbg", "noLinkInserted"))
doc164.iconSrc = ICONPATH + "fileok.gif"
doc165 = insDoc(libbb, gLnk("S", "bb_basename.dbg", "noLinkInserted"))
doc165.iconSrc = ICONPATH + "fileok.gif"
doc166 = insDoc(libbb, gLnk("S", "bb_bswap_64.dbg", "noLinkInserted"))
doc166.iconSrc = ICONPATH + "fileok.gif"
doc167 = insDoc(libbb, gLnk("S", "bb_do_delay.dbg", "noLinkInserted"))
doc167.iconSrc = ICONPATH + "fileok.gif"
doc168 = insDoc(libbb, gLnk("S", "bb_pwd.dbg", "noLinkInserted"))
doc168.iconSrc = ICONPATH + "fileok.gif"
doc169 = insDoc(libbb, gLnk("S", "bb_qsort.dbg", "noLinkInserted"))
doc169.iconSrc = ICONPATH + "fileok.gif"
doc170 = insDoc(libbb, gLnk("S", "bb_strtonum.dbg", "noLinkInserted"))
doc170.iconSrc = ICONPATH + "fileok.gif"
doc171 = insDoc(libbb, gLnk("S", "change_identity.dbg", "noLinkInserted"))
doc171.iconSrc = ICONPATH + "fileok.gif"
doc172 = insDoc(libbb, gLnk("S", "chomp.dbg", "noLinkInserted"))
doc172.iconSrc = ICONPATH + "fileok.gif"
doc173 = insDoc(libbb, gLnk("S", "compare_string_array.dbg", "noLinkInserted"))
doc173.iconSrc = ICONPATH + "fileok.gif"
doc174 = insDoc(libbb, gLnk("S", "concat_path_file.dbg", "noLinkInserted"))
doc174.iconSrc = ICONPATH + "fileok.gif"
doc175 = insDoc(libbb, gLnk("S", "concat_subpath_file.dbg", "noLinkInserted"))
doc175.iconSrc = ICONPATH + "fileok.gif"
doc176 = insDoc(libbb, gLnk("S", "copy_file.dbg", "noLinkInserted"))
doc176.iconSrc = ICONPATH + "fileok.gif"
doc177 = insDoc(libbb, gLnk("S", "copyfd.dbg", "noLinkInserted"))
doc177.iconSrc = ICONPATH + "fileok.gif"
doc178 = insDoc(libbb, gLnk("S", "correct_password.dbg", "noLinkInserted"))
doc178.iconSrc = ICONPATH + "fileok.gif"
doc179 = insDoc(libbb, gLnk("S", "crc32.dbg", "noLinkInserted"))
doc179.iconSrc = ICONPATH + "fileok.gif"
doc180 = insDoc(libbb, gLnk("S", "create_icmp6_socket.dbg", "noLinkInserted"))
doc180.iconSrc = ICONPATH + "fileok.gif"
doc181 = insDoc(libbb, gLnk("S", "create_icmp_socket.dbg", "noLinkInserted"))
doc181.iconSrc = ICONPATH + "fileok.gif"
doc182 = insDoc(libbb, gLnk("S", "default_error_retval.dbg", "noLinkInserted"))
doc182.iconSrc = ICONPATH + "fileok.gif"
doc183 = insDoc(libbb, gLnk("S", "device_open.dbg", "noLinkInserted"))
doc183.iconSrc = ICONPATH + "fileok.gif"
doc184 = insDoc(libbb, gLnk("S", "die_if_bad_username.dbg", "noLinkInserted"))
doc184.iconSrc = ICONPATH + "fileok.gif"
doc185 = insDoc(libbb, gLnk("S", "dump.dbg", "noLinkInserted"))
doc185.iconSrc = ICONPATH + "fileok.gif"
doc186 = insDoc(libbb, gLnk("S", "execable.dbg", "noLinkInserted"))
doc186.iconSrc = ICONPATH + "fileok.gif"
doc187 = insDoc(libbb, gLnk("S", "fclose_nonstdin.dbg", "noLinkInserted"))
doc187.iconSrc = ICONPATH + "fileok.gif"
doc188 = insDoc(libbb, gLnk("S", "fflush_stdout_and_exit.dbg", "noLinkInserted"))
doc188.iconSrc = ICONPATH + "fileok.gif"
doc189 = insDoc(libbb, gLnk("S", "fgets_str.dbg", "noLinkInserted"))
doc189.iconSrc = ICONPATH + "fileok.gif"
doc190 = insDoc(libbb, gLnk("S", "find_mount_point.dbg", "noLinkInserted"))
doc190.iconSrc = ICONPATH + "fileok.gif"
doc191 = insDoc(libbb, gLnk("S", "find_pid_by_name.dbg", "noLinkInserted"))
doc191.iconSrc = ICONPATH + "fileok.gif"
doc192 = insDoc(libbb, gLnk("S", "find_root_device.dbg", "noLinkInserted"))
doc192.iconSrc = ICONPATH + "fileok.gif"
doc193 = insDoc(libbb, gLnk("S", "full_write.dbg", "noLinkInserted"))
doc193.iconSrc = ICONPATH + "fileok.gif"
doc194 = insDoc(libbb, gLnk("S", "get_console.dbg", "noLinkInserted"))
doc194.iconSrc = ICONPATH + "fileok.gif"
doc195 = insDoc(libbb, gLnk("S", "get_cpu_count.dbg", "noLinkInserted"))
doc195.iconSrc = ICONPATH + "fileok.gif"
doc196 = insDoc(libbb, gLnk("S", "get_last_path_component.dbg", "noLinkInserted"))
doc196.iconSrc = ICONPATH + "fileok.gif"
doc197 = insDoc(libbb, gLnk("S", "get_line_from_file.dbg", "noLinkInserted"))
doc197.iconSrc = ICONPATH + "fileok.gif"
doc198 = insDoc(libbb, gLnk("S", "get_volsize.dbg", "noLinkInserted"))
doc198.iconSrc = ICONPATH + "fileok.gif"
doc199 = insDoc(libbb, gLnk("S", "getopt32.dbg", "noLinkInserted"))
doc199.iconSrc = ICONPATH + "fileok.gif"
doc200 = insDoc(libbb, gLnk("S", "getpty.dbg", "noLinkInserted"))
doc200.iconSrc = ICONPATH + "filefail.gif"
doc201 = insDoc(libbb, gLnk("S", "hash_md5_sha.dbg", "noLinkInserted"))
doc201.iconSrc = ICONPATH + "fileok.gif"
doc202 = insDoc(libbb, gLnk("S", "herror_msg.dbg", "noLinkInserted"))
doc202.iconSrc = ICONPATH + "fileok.gif"
doc203 = insDoc(libbb, gLnk("S", "human_readable.dbg", "noLinkInserted"))
doc203.iconSrc = ICONPATH + "fileok.gif"
doc204 = insDoc(libbb, gLnk("S", "inet_common.dbg", "noLinkInserted"))
doc204.iconSrc = ICONPATH + "fileok.gif"
doc205 = insDoc(libbb, gLnk("S", "info_msg.dbg", "noLinkInserted"))
doc205.iconSrc = ICONPATH + "filefail.gif"
doc206 = insDoc(libbb, gLnk("S", "inode_hash.dbg", "noLinkInserted"))
doc206.iconSrc = ICONPATH + "fileok.gif"
doc207 = insDoc(libbb, gLnk("S", "isdirectory.dbg", "noLinkInserted"))
doc207.iconSrc = ICONPATH + "fileok.gif"
doc208 = insDoc(libbb, gLnk("S", "kernel_version.dbg", "noLinkInserted"))
doc208.iconSrc = ICONPATH + "fileok.gif"
doc209 = insDoc(libbb, gLnk("S", "last_char_is.dbg", "noLinkInserted"))
doc209.iconSrc = ICONPATH + "fileok.gif"
doc210 = insDoc(libbb, gLnk("S", "lineedit.dbg", "noLinkInserted"))
doc210.iconSrc = ICONPATH + "filefail.gif"
doc211 = insDoc(libbb, gLnk("S", "lineedit_ptr_hack.dbg", "noLinkInserted"))
doc211.iconSrc = ICONPATH + "fileok.gif"
doc212 = insDoc(libbb, gLnk("S", "llist.dbg", "noLinkInserted"))
doc212.iconSrc = ICONPATH + "fileok.gif"
doc213 = insDoc(libbb, gLnk("S", "login.dbg", "noLinkInserted"))
doc213.iconSrc = ICONPATH + "filefail.gif"
doc214 = insDoc(libbb, gLnk("S", "loop.dbg", "noLinkInserted"))
doc214.iconSrc = ICONPATH + "fileok.gif"
doc215 = insDoc(libbb, gLnk("S", "make_directory.dbg", "noLinkInserted"))
doc215.iconSrc = ICONPATH + "fileok.gif"
doc216 = insDoc(libbb, gLnk("S", "makedev.dbg", "noLinkInserted"))
doc216.iconSrc = ICONPATH + "fileok.gif"
doc217 = insDoc(libbb, gLnk("S", "match_fstype.dbg", "noLinkInserted"))
doc217.iconSrc = ICONPATH + "fileok.gif"
doc218 = insDoc(libbb, gLnk("S", "messages.dbg", "noLinkInserted"))
doc218.iconSrc = ICONPATH + "fileok.gif"
doc219 = insDoc(libbb, gLnk("S", "mode_string.dbg", "noLinkInserted"))
doc219.iconSrc = ICONPATH + "fileok.gif"
doc220 = insDoc(libbb, gLnk("S", "mtab.dbg", "noLinkInserted"))
doc220.iconSrc = ICONPATH + "fileok.gif"
doc221 = insDoc(libbb, gLnk("S", "obscure.dbg", "noLinkInserted"))
doc221.iconSrc = ICONPATH + "filefail.gif"
doc222 = insDoc(libbb, gLnk("S", "parse_config.dbg", "noLinkInserted"))
doc222.iconSrc = ICONPATH + "filefail.gif"
doc223 = insDoc(libbb, gLnk("S", "parse_mode.dbg", "noLinkInserted"))
doc223.iconSrc = ICONPATH + "fileok.gif"
doc224 = insDoc(libbb, gLnk("S", "perror_msg.dbg", "noLinkInserted"))
doc224.iconSrc = ICONPATH + "fileok.gif"
doc225 = insDoc(libbb, gLnk("S", "perror_nomsg.dbg", "noLinkInserted"))
doc225.iconSrc = ICONPATH + "fileok.gif"
doc226 = insDoc(libbb, gLnk("S", "perror_nomsg_and_die.dbg", "noLinkInserted"))
doc226.iconSrc = ICONPATH + "fileok.gif"
doc227 = insDoc(libbb, gLnk("S", "pidfile.dbg", "noLinkInserted"))
doc227.iconSrc = ICONPATH + "fileok.gif"
doc228 = insDoc(libbb, gLnk("S", "platform.dbg", "noLinkInserted"))
doc228.iconSrc = ICONPATH + "fileok.gif"
doc229 = insDoc(libbb, gLnk("S", "print_flags.dbg", "noLinkInserted"))
doc229.iconSrc = ICONPATH + "fileok.gif"
doc230 = insDoc(libbb, gLnk("S", "printable.dbg", "noLinkInserted"))
doc230.iconSrc = ICONPATH + "fileok.gif"
doc231 = insDoc(libbb, gLnk("S", "printable_string.dbg", "noLinkInserted"))
doc231.iconSrc = ICONPATH + "fileok.gif"
doc232 = insDoc(libbb, gLnk("S", "process_escape_sequence.dbg", "noLinkInserted"))
doc232.iconSrc = ICONPATH + "fileok.gif"
doc233 = insDoc(libbb, gLnk("S", "procps.dbg", "noLinkInserted"))
doc233.iconSrc = ICONPATH + "fileok.gif"
doc234 = insDoc(libbb, gLnk("S", "progress.dbg", "noLinkInserted"))
doc234.iconSrc = ICONPATH + "fileok.gif"
doc235 = insDoc(libbb, gLnk("S", "ptr_to_globals.dbg", "noLinkInserted"))
doc235.iconSrc = ICONPATH + "fileok.gif"
doc236 = insDoc(libbb, gLnk("S", "pw_encrypt.dbg", "noLinkInserted"))
doc236.iconSrc = ICONPATH + "filefail.gif"
doc237 = insDoc(libbb, gLnk("S", "read.dbg", "noLinkInserted"))
doc237.iconSrc = ICONPATH + "fileok.gif"
doc238 = insDoc(libbb, gLnk("S", "read_key.dbg", "noLinkInserted"))
doc238.iconSrc = ICONPATH + "fileok.gif"
doc239 = insDoc(libbb, gLnk("S", "read_printf.dbg", "noLinkInserted"))
doc239.iconSrc = ICONPATH + "fileok.gif"
doc240 = insDoc(libbb, gLnk("S", "recursive_action.dbg", "noLinkInserted"))
doc240.iconSrc = ICONPATH + "fileok.gif"
doc241 = insDoc(libbb, gLnk("S", "remove_file.dbg", "noLinkInserted"))
doc241.iconSrc = ICONPATH + "fileok.gif"
doc242 = insDoc(libbb, gLnk("S", "rtc.dbg", "noLinkInserted"))
doc242.iconSrc = ICONPATH + "fileok.gif"
doc243 = insDoc(libbb, gLnk("S", "run_shell.dbg", "noLinkInserted"))
doc243.iconSrc = ICONPATH + "fileok.gif"
doc244 = insDoc(libbb, gLnk("S", "safe_gethostname.dbg", "noLinkInserted"))
doc244.iconSrc = ICONPATH + "filefail.gif"
doc245 = insDoc(libbb, gLnk("S", "safe_poll.dbg", "noLinkInserted"))
doc245.iconSrc = ICONPATH + "fileok.gif"
doc246 = insDoc(libbb, gLnk("S", "safe_strncpy.dbg", "noLinkInserted"))
doc246.iconSrc = ICONPATH + "fileok.gif"
doc247 = insDoc(libbb, gLnk("S", "safe_write.dbg", "noLinkInserted"))
doc247.iconSrc = ICONPATH + "fileok.gif"
doc248 = insDoc(libbb, gLnk("S", "selinux_common.dbg", "noLinkInserted"))
doc248.iconSrc = ICONPATH + "fileok.gif"
doc249 = insDoc(libbb, gLnk("S", "setup_environment.dbg", "noLinkInserted"))
doc249.iconSrc = ICONPATH + "fileok.gif"
doc250 = insDoc(libbb, gLnk("S", "signals.dbg", "noLinkInserted"))
doc250.iconSrc = ICONPATH + "fileok.gif"
doc251 = insDoc(libbb, gLnk("S", "simplify_path.dbg", "noLinkInserted"))
doc251.iconSrc = ICONPATH + "fileok.gif"
doc252 = insDoc(libbb, gLnk("S", "single_argv.dbg", "noLinkInserted"))
doc252.iconSrc = ICONPATH + "fileok.gif"
doc253 = insDoc(libbb, gLnk("S", "skip_whitespace.dbg", "noLinkInserted"))
doc253.iconSrc = ICONPATH + "fileok.gif"
doc254 = insDoc(libbb, gLnk("S", "speed_table.dbg", "noLinkInserted"))
doc254.iconSrc = ICONPATH + "fileok.gif"
doc255 = insDoc(libbb, gLnk("S", "str_tolower.dbg", "noLinkInserted"))
doc255.iconSrc = ICONPATH + "fileok.gif"
doc256 = insDoc(libbb, gLnk("S", "strrstr.dbg", "noLinkInserted"))
doc256.iconSrc = ICONPATH + "fileok.gif"
doc257 = insDoc(libbb, gLnk("S", "time.dbg", "noLinkInserted"))
doc257.iconSrc = ICONPATH + "filefail.gif"
doc258 = insDoc(libbb, gLnk("S", "trim.dbg", "noLinkInserted"))
doc258.iconSrc = ICONPATH + "fileok.gif"
doc259 = insDoc(libbb, gLnk("S", "u_signal_names.dbg", "noLinkInserted"))
doc259.iconSrc = ICONPATH + "fileok.gif"
doc260 = insDoc(libbb, gLnk("S", "udp_io.dbg", "noLinkInserted"))
doc260.iconSrc = ICONPATH + "filefail.gif"
doc261 = insDoc(libbb, gLnk("S", "unicode.dbg", "noLinkInserted"))
doc261.iconSrc = ICONPATH + "filefail.gif"
doc262 = insDoc(libbb, gLnk("S", "update_passwd.dbg", "noLinkInserted"))
doc262.iconSrc = ICONPATH + "filefail.gif"
doc263 = insDoc(libbb, gLnk("S", "utmp.dbg", "noLinkInserted"))
doc263.iconSrc = ICONPATH + "fileok.gif"
doc264 = insDoc(libbb, gLnk("S", "uuencode.dbg", "noLinkInserted"))
doc264.iconSrc = ICONPATH + "fileok.gif"
doc265 = insDoc(libbb, gLnk("S", "vdprintf.dbg", "noLinkInserted"))
doc265.iconSrc = ICONPATH + "fileok.gif"
doc266 = insDoc(libbb, gLnk("S", "verror_msg.dbg", "noLinkInserted"))
doc266.iconSrc = ICONPATH + "filefail.gif"
doc267 = insDoc(libbb, gLnk("S", "vfork_daemon_rexec.dbg", "noLinkInserted"))
doc267.iconSrc = ICONPATH + "fileok.gif"
doc268 = insDoc(libbb, gLnk("S", "warn_ignoring_args.dbg", "noLinkInserted"))
doc268.iconSrc = ICONPATH + "fileok.gif"
doc269 = insDoc(libbb, gLnk("S", "wfopen.dbg", "noLinkInserted"))
doc269.iconSrc = ICONPATH + "fileok.gif"
doc270 = insDoc(libbb, gLnk("S", "wfopen_input.dbg", "noLinkInserted"))
doc270.iconSrc = ICONPATH + "fileok.gif"
doc271 = insDoc(libbb, gLnk("S", "write.dbg", "noLinkInserted"))
doc271.iconSrc = ICONPATH + "fileok.gif"
doc272 = insDoc(libbb, gLnk("S", "xatonum.dbg", "noLinkInserted"))
doc272.iconSrc = ICONPATH + "fileok.gif"
doc273 = insDoc(libbb, gLnk("S", "xconnect.dbg", "noLinkInserted"))
doc273.iconSrc = ICONPATH + "fileok.gif"
doc274 = insDoc(libbb, gLnk("S", "xfunc_die.dbg", "noLinkInserted"))
doc274.iconSrc = ICONPATH + "fileok.gif"
doc275 = insDoc(libbb, gLnk("S", "xfuncs.dbg", "noLinkInserted"))
doc275.iconSrc = ICONPATH + "fileok.gif"
doc276 = insDoc(libbb, gLnk("S", "xfuncs_printf.dbg", "noLinkInserted"))
doc276.iconSrc = ICONPATH + "filefail.gif"
doc277 = insDoc(libbb, gLnk("S", "xgetcwd.dbg", "noLinkInserted"))
doc277.iconSrc = ICONPATH + "fileok.gif"
doc278 = insDoc(libbb, gLnk("S", "xgethostbyname.dbg", "noLinkInserted"))
doc278.iconSrc = ICONPATH + "fileok.gif"
doc279 = insDoc(libbb, gLnk("S", "xreadlink.dbg", "noLinkInserted"))
doc279.iconSrc = ICONPATH + "fileok.gif"
doc280 = insDoc(libbb, gLnk("S", "xrealloc_vector.dbg", "noLinkInserted"))
doc280.iconSrc = ICONPATH + "fileok.gif"
doc281 = insDoc(libbb, gLnk("S", "xregcomp.dbg", "noLinkInserted"))
doc281.iconSrc = ICONPATH + "fileok.gif"
libpwdgrp = insFld(foldersTree, gFld("libpwdgrp", ""))
libpwdgrp.iconSrc = ICONPATH + "folderopenok.gif"
libpwdgrp.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc282 = insDoc(libpwdgrp, gLnk("S", "pwd_grp.dbg", "noLinkInserted"))
doc282.iconSrc = ICONPATH + "fileok.gif"
doc283 = insDoc(libpwdgrp, gLnk("S", "uidgid_get.dbg", "noLinkInserted"))
doc283.iconSrc = ICONPATH + "fileok.gif"
loginutils = insFld(foldersTree, gFld("loginutils", ""))
loginutils.iconSrc = ICONPATH + "folderopenok.gif"
loginutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc284 = insDoc(loginutils, gLnk("S", "add-remove-shell.dbg", "noLinkInserted"))
doc284.iconSrc = ICONPATH + "fileok.gif"
doc285 = insDoc(loginutils, gLnk("S", "addgroup.dbg", "noLinkInserted"))
doc285.iconSrc = ICONPATH + "fileok.gif"
doc286 = insDoc(loginutils, gLnk("S", "adduser.dbg", "noLinkInserted"))
doc286.iconSrc = ICONPATH + "fileok.gif"
doc287 = insDoc(loginutils, gLnk("S", "chpasswd.dbg", "noLinkInserted"))
doc287.iconSrc = ICONPATH + "fileok.gif"
doc288 = insDoc(loginutils, gLnk("S", "cryptpw.dbg", "noLinkInserted"))
doc288.iconSrc = ICONPATH + "fileok.gif"
doc289 = insDoc(loginutils, gLnk("S", "deluser.dbg", "noLinkInserted"))
doc289.iconSrc = ICONPATH + "fileok.gif"
doc290 = insDoc(loginutils, gLnk("S", "getty.dbg", "noLinkInserted"))
doc290.iconSrc = ICONPATH + "fileok.gif"
doc291 = insDoc(loginutils, gLnk("S", "login.dbg", "noLinkInserted"))
doc291.iconSrc = ICONPATH + "fileok.gif"
doc292 = insDoc(loginutils, gLnk("S", "passwd.dbg", "noLinkInserted"))
doc292.iconSrc = ICONPATH + "fileok.gif"
doc293 = insDoc(loginutils, gLnk("S", "su.dbg", "noLinkInserted"))
doc293.iconSrc = ICONPATH + "fileok.gif"
doc294 = insDoc(loginutils, gLnk("S", "sulogin.dbg", "noLinkInserted"))
doc294.iconSrc = ICONPATH + "fileok.gif"
doc295 = insDoc(loginutils, gLnk("S", "vlock.dbg", "noLinkInserted"))
doc295.iconSrc = ICONPATH + "fileok.gif"
mailutils = insFld(foldersTree, gFld("mailutils", ""))
mailutils.iconSrc = ICONPATH + "folderopenfail.gif"
mailutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc296 = insDoc(mailutils, gLnk("S", "mail.dbg", "noLinkInserted"))
doc296.iconSrc = ICONPATH + "fileok.gif"
doc297 = insDoc(mailutils, gLnk("S", "mime.dbg", "noLinkInserted"))
doc297.iconSrc = ICONPATH + "filefail.gif"
doc298 = insDoc(mailutils, gLnk("S", "popmaildir.dbg", "noLinkInserted"))
doc298.iconSrc = ICONPATH + "fileok.gif"
doc299 = insDoc(mailutils, gLnk("S", "sendmail.dbg", "noLinkInserted"))
doc299.iconSrc = ICONPATH + "fileok.gif"
miscutils = insFld(foldersTree, gFld("miscutils", ""))
miscutils.iconSrc = ICONPATH + "folderopenfail.gif"
miscutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc300 = insDoc(miscutils, gLnk("S", "adjtimex.dbg", "noLinkInserted"))
doc300.iconSrc = ICONPATH + "fileok.gif"
doc301 = insDoc(miscutils, gLnk("S", "bbconfig.dbg", "noLinkInserted"))
doc301.iconSrc = ICONPATH + "fileok.gif"
doc302 = insDoc(miscutils, gLnk("S", "beep.dbg", "noLinkInserted"))
doc302.iconSrc = ICONPATH + "fileok.gif"
doc303 = insDoc(miscutils, gLnk("S", "chat.dbg", "noLinkInserted"))
doc303.iconSrc = ICONPATH + "fileok.gif"
doc304 = insDoc(miscutils, gLnk("S", "chrt.dbg", "noLinkInserted"))
doc304.iconSrc = ICONPATH + "fileok.gif"
doc305 = insDoc(miscutils, gLnk("S", "conspy.dbg", "noLinkInserted"))
doc305.iconSrc = ICONPATH + "fileok.gif"
doc306 = insDoc(miscutils, gLnk("S", "crond.dbg", "noLinkInserted"))
doc306.iconSrc = ICONPATH + "filefail.gif"
doc307 = insDoc(miscutils, gLnk("S", "crontab.dbg", "noLinkInserted"))
doc307.iconSrc = ICONPATH + "fileok.gif"
doc308 = insDoc(miscutils, gLnk("S", "dc.dbg", "noLinkInserted"))
doc308.iconSrc = ICONPATH + "filefail.gif"
doc309 = insDoc(miscutils, gLnk("S", "devfsd.dbg", "noLinkInserted"))
doc309.iconSrc = ICONPATH + "fileok.gif"
doc310 = insDoc(miscutils, gLnk("S", "devmem.dbg", "noLinkInserted"))
doc310.iconSrc = ICONPATH + "filefail.gif"
doc311 = insDoc(miscutils, gLnk("S", "eject.dbg", "noLinkInserted"))
doc311.iconSrc = ICONPATH + "fileok.gif"
doc312 = insDoc(miscutils, gLnk("S", "fbsplash.dbg", "noLinkInserted"))
doc312.iconSrc = ICONPATH + "filefail.gif"
doc313 = insDoc(miscutils, gLnk("S", "flash_eraseall.dbg", "noLinkInserted"))
doc313.iconSrc = ICONPATH + "fileok.gif"
doc314 = insDoc(miscutils, gLnk("S", "flash_lock_unlock.dbg", "noLinkInserted"))
doc314.iconSrc = ICONPATH + "fileok.gif"
doc315 = insDoc(miscutils, gLnk("S", "flashcp.dbg", "noLinkInserted"))
doc315.iconSrc = ICONPATH + "fileok.gif"
doc316 = insDoc(miscutils, gLnk("S", "hdparm.dbg", "noLinkInserted"))
doc316.iconSrc = ICONPATH + "fileok.gif"
doc317 = insDoc(miscutils, gLnk("S", "inotifyd.dbg", "noLinkInserted"))
doc317.iconSrc = ICONPATH + "fileok.gif"
doc318 = insDoc(miscutils, gLnk("S", "ionice.dbg", "noLinkInserted"))
doc318.iconSrc = ICONPATH + "fileok.gif"
doc319 = insDoc(miscutils, gLnk("S", "last.dbg", "noLinkInserted"))
doc319.iconSrc = ICONPATH + "fileok.gif"
doc320 = insDoc(miscutils, gLnk("S", "last_fancy.dbg", "noLinkInserted"))
doc320.iconSrc = ICONPATH + "fileok.gif"
doc321 = insDoc(miscutils, gLnk("S", "less.dbg", "noLinkInserted"))
doc321.iconSrc = ICONPATH + "fileok.gif"
doc322 = insDoc(miscutils, gLnk("S", "makedevs.dbg", "noLinkInserted"))
doc322.iconSrc = ICONPATH + "fileok.gif"
doc323 = insDoc(miscutils, gLnk("S", "man.dbg", "noLinkInserted"))
doc323.iconSrc = ICONPATH + "filefail.gif"
doc324 = insDoc(miscutils, gLnk("S", "microcom.dbg", "noLinkInserted"))
doc324.iconSrc = ICONPATH + "fileok.gif"
doc325 = insDoc(miscutils, gLnk("S", "mountpoint.dbg", "noLinkInserted"))
doc325.iconSrc = ICONPATH + "fileok.gif"
doc326 = insDoc(miscutils, gLnk("S", "mt.dbg", "noLinkInserted"))
doc326.iconSrc = ICONPATH + "fileok.gif"
doc327 = insDoc(miscutils, gLnk("S", "nandwrite.dbg", "noLinkInserted"))
doc327.iconSrc = ICONPATH + "fileok.gif"
doc328 = insDoc(miscutils, gLnk("S", "raidautorun.dbg", "noLinkInserted"))
doc328.iconSrc = ICONPATH + "fileok.gif"
doc329 = insDoc(miscutils, gLnk("S", "readahead.dbg", "noLinkInserted"))
doc329.iconSrc = ICONPATH + "filefail.gif"
doc330 = insDoc(miscutils, gLnk("S", "rfkill.dbg", "noLinkInserted"))
doc330.iconSrc = ICONPATH + "fileok.gif"
doc331 = insDoc(miscutils, gLnk("S", "runlevel.dbg", "noLinkInserted"))
doc331.iconSrc = ICONPATH + "fileok.gif"
doc332 = insDoc(miscutils, gLnk("S", "rx.dbg", "noLinkInserted"))
doc332.iconSrc = ICONPATH + "fileok.gif"
doc333 = insDoc(miscutils, gLnk("S", "setsid.dbg", "noLinkInserted"))
doc333.iconSrc = ICONPATH + "fileok.gif"
doc334 = insDoc(miscutils, gLnk("S", "strings.dbg", "noLinkInserted"))
doc334.iconSrc = ICONPATH + "fileok.gif"
doc335 = insDoc(miscutils, gLnk("S", "taskset.dbg", "noLinkInserted"))
doc335.iconSrc = ICONPATH + "filefail.gif"
doc336 = insDoc(miscutils, gLnk("S", "time.dbg", "noLinkInserted"))
doc336.iconSrc = ICONPATH + "fileok.gif"
doc337 = insDoc(miscutils, gLnk("S", "timeout.dbg", "noLinkInserted"))
doc337.iconSrc = ICONPATH + "fileok.gif"
doc338 = insDoc(miscutils, gLnk("S", "ttysize.dbg", "noLinkInserted"))
doc338.iconSrc = ICONPATH + "fileok.gif"
doc339 = insDoc(miscutils, gLnk("S", "ubi_attach_detach.dbg", "noLinkInserted"))
doc339.iconSrc = ICONPATH + "fileok.gif"
doc340 = insDoc(miscutils, gLnk("S", "volname.dbg", "noLinkInserted"))
doc340.iconSrc = ICONPATH + "fileok.gif"
doc341 = insDoc(miscutils, gLnk("S", "wall.dbg", "noLinkInserted"))
doc341.iconSrc = ICONPATH + "fileok.gif"
doc342 = insDoc(miscutils, gLnk("S", "watchdog.dbg", "noLinkInserted"))
doc342.iconSrc = ICONPATH + "fileok.gif"
modutils = insFld(foldersTree, gFld("modutils", ""))
modutils.iconSrc = ICONPATH + "folderopenfail.gif"
modutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc343 = insDoc(modutils, gLnk("S", "depmod.dbg", "noLinkInserted"))
doc343.iconSrc = ICONPATH + "filefail.gif"
doc344 = insDoc(modutils, gLnk("S", "insmod.dbg", "noLinkInserted"))
doc344.iconSrc = ICONPATH + "fileok.gif"
doc345 = insDoc(modutils, gLnk("S", "lsmod.dbg", "noLinkInserted"))
doc345.iconSrc = ICONPATH + "fileok.gif"
doc346 = insDoc(modutils, gLnk("S", "modinfo.dbg", "noLinkInserted"))
doc346.iconSrc = ICONPATH + "fileok.gif"
doc347 = insDoc(modutils, gLnk("S", "modprobe-small.dbg", "noLinkInserted"))
doc347.iconSrc = ICONPATH + "filefail.gif"
doc348 = insDoc(modutils, gLnk("S", "modprobe.dbg", "noLinkInserted"))
doc348.iconSrc = ICONPATH + "fileok.gif"
doc349 = insDoc(modutils, gLnk("S", "modutils-24.dbg", "noLinkInserted"))
doc349.iconSrc = ICONPATH + "filefail.gif"
doc350 = insDoc(modutils, gLnk("S", "modutils.dbg", "noLinkInserted"))
doc350.iconSrc = ICONPATH + "fileok.gif"
doc351 = insDoc(modutils, gLnk("S", "rmmod.dbg", "noLinkInserted"))
doc351.iconSrc = ICONPATH + "fileok.gif"
networking = insFld(foldersTree, gFld("networking", ""))
networking.iconSrc = ICONPATH + "folderopenfail.gif"
networking.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc352 = insDoc(networking, gLnk("S", "arp.dbg", "noLinkInserted"))
doc352.iconSrc = ICONPATH + "fileok.gif"
doc353 = insDoc(networking, gLnk("S", "arping.dbg", "noLinkInserted"))
doc353.iconSrc = ICONPATH + "filefail.gif"
doc354 = insDoc(networking, gLnk("S", "brctl.dbg", "noLinkInserted"))
doc354.iconSrc = ICONPATH + "fileok.gif"
doc355 = insDoc(networking, gLnk("S", "dnsd.dbg", "noLinkInserted"))
doc355.iconSrc = ICONPATH + "fileok.gif"
doc356 = insDoc(networking, gLnk("S", "ether-wake.dbg", "noLinkInserted"))
doc356.iconSrc = ICONPATH + "fileok.gif"
doc357 = insDoc(networking, gLnk("S", "ftpd.dbg", "noLinkInserted"))
doc357.iconSrc = ICONPATH + "filefail.gif"
doc358 = insDoc(networking, gLnk("S", "ftpgetput.dbg", "noLinkInserted"))
doc358.iconSrc = ICONPATH + "fileok.gif"
doc359 = insDoc(networking, gLnk("S", "hostname.dbg", "noLinkInserted"))
doc359.iconSrc = ICONPATH + "filefail.gif"
doc360 = insDoc(networking, gLnk("S", "httpd.dbg", "noLinkInserted"))
doc360.iconSrc = ICONPATH + "filefail.gif"
doc361 = insDoc(networking, gLnk("S", "ifconfig.dbg", "noLinkInserted"))
doc361.iconSrc = ICONPATH + "fileok.gif"
doc362 = insDoc(networking, gLnk("S", "ifenslave.dbg", "noLinkInserted"))
doc362.iconSrc = ICONPATH + "fileok.gif"
doc363 = insDoc(networking, gLnk("S", "ifplugd.dbg", "noLinkInserted"))
doc363.iconSrc = ICONPATH + "fileok.gif"
doc364 = insDoc(networking, gLnk("S", "ifupdown.dbg", "noLinkInserted"))
doc364.iconSrc = ICONPATH + "fileok.gif"
doc365 = insDoc(networking, gLnk("S", "inetd.dbg", "noLinkInserted"))
doc365.iconSrc = ICONPATH + "fileok.gif"
doc366 = insDoc(networking, gLnk("S", "interface.dbg", "noLinkInserted"))
doc366.iconSrc = ICONPATH + "fileok.gif"
doc367 = insDoc(networking, gLnk("S", "ip.dbg", "noLinkInserted"))
doc367.iconSrc = ICONPATH + "fileok.gif"
doc368 = insDoc(networking, gLnk("S", "ipcalc.dbg", "noLinkInserted"))
doc368.iconSrc = ICONPATH + "fileok.gif"
doc369 = insDoc(networking, gLnk("S", "isrv.dbg", "noLinkInserted"))
doc369.iconSrc = ICONPATH + "fileok.gif"
doc370 = insDoc(networking, gLnk("S", "isrv_identd.dbg", "noLinkInserted"))
doc370.iconSrc = ICONPATH + "fileok.gif"
libiproute = insFld(networking, gFld("libiproute", ""))
libiproute.iconSrc = ICONPATH + "folderopenok.gif"
libiproute.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc371 = insDoc(libiproute, gLnk("S", "ip_parse_common_args.dbg", "noLinkInserted"))
doc371.iconSrc = ICONPATH + "fileok.gif"
doc372 = insDoc(libiproute, gLnk("S", "ipaddress.dbg", "noLinkInserted"))
doc372.iconSrc = ICONPATH + "fileok.gif"
doc373 = insDoc(libiproute, gLnk("S", "iplink.dbg", "noLinkInserted"))
doc373.iconSrc = ICONPATH + "fileok.gif"
doc374 = insDoc(libiproute, gLnk("S", "iproute.dbg", "noLinkInserted"))
doc374.iconSrc = ICONPATH + "fileok.gif"
doc375 = insDoc(libiproute, gLnk("S", "iprule.dbg", "noLinkInserted"))
doc375.iconSrc = ICONPATH + "fileok.gif"
doc376 = insDoc(libiproute, gLnk("S", "iptunnel.dbg", "noLinkInserted"))
doc376.iconSrc = ICONPATH + "fileok.gif"
doc377 = insDoc(libiproute, gLnk("S", "libnetlink.dbg", "noLinkInserted"))
doc377.iconSrc = ICONPATH + "fileok.gif"
doc378 = insDoc(libiproute, gLnk("S", "ll_addr.dbg", "noLinkInserted"))
doc378.iconSrc = ICONPATH + "fileok.gif"
doc379 = insDoc(libiproute, gLnk("S", "ll_map.dbg", "noLinkInserted"))
doc379.iconSrc = ICONPATH + "fileok.gif"
doc380 = insDoc(libiproute, gLnk("S", "ll_proto.dbg", "noLinkInserted"))
doc380.iconSrc = ICONPATH + "fileok.gif"
doc381 = insDoc(libiproute, gLnk("S", "ll_types.dbg", "noLinkInserted"))
doc381.iconSrc = ICONPATH + "fileok.gif"
doc382 = insDoc(libiproute, gLnk("S", "rt_names.dbg", "noLinkInserted"))
doc382.iconSrc = ICONPATH + "fileok.gif"
doc383 = insDoc(libiproute, gLnk("S", "rtm_map.dbg", "noLinkInserted"))
doc383.iconSrc = ICONPATH + "fileok.gif"
doc384 = insDoc(libiproute, gLnk("S", "utils.dbg", "noLinkInserted"))
doc384.iconSrc = ICONPATH + "fileok.gif"
doc385 = insDoc(networking, gLnk("S", "nameif.dbg", "noLinkInserted"))
doc385.iconSrc = ICONPATH + "fileok.gif"
doc386 = insDoc(networking, gLnk("S", "nbd-client.dbg", "noLinkInserted"))
doc386.iconSrc = ICONPATH + "fileok.gif"
doc387 = insDoc(networking, gLnk("S", "nc.dbg", "noLinkInserted"))
doc387.iconSrc = ICONPATH + "fileok.gif"
doc388 = insDoc(networking, gLnk("S", "netstat.dbg", "noLinkInserted"))
doc388.iconSrc = ICONPATH + "filefail.gif"
doc389 = insDoc(networking, gLnk("S", "nslookup.dbg", "noLinkInserted"))
doc389.iconSrc = ICONPATH + "fileok.gif"
doc390 = insDoc(networking, gLnk("S", "ntpd.dbg", "noLinkInserted"))
doc390.iconSrc = ICONPATH + "fileok.gif"
doc391 = insDoc(networking, gLnk("S", "ping.dbg", "noLinkInserted"))
doc391.iconSrc = ICONPATH + "fileok.gif"
doc392 = insDoc(networking, gLnk("S", "pscan.dbg", "noLinkInserted"))
doc392.iconSrc = ICONPATH + "fileok.gif"
doc393 = insDoc(networking, gLnk("S", "route.dbg", "noLinkInserted"))
doc393.iconSrc = ICONPATH + "fileok.gif"
doc394 = insDoc(networking, gLnk("S", "slattach.dbg", "noLinkInserted"))
doc394.iconSrc = ICONPATH + "fileok.gif"
doc395 = insDoc(networking, gLnk("S", "tcpudp.dbg", "noLinkInserted"))
doc395.iconSrc = ICONPATH + "fileok.gif"
doc396 = insDoc(networking, gLnk("S", "tcpudp_perhost.dbg", "noLinkInserted"))
doc396.iconSrc = ICONPATH + "fileok.gif"
doc397 = insDoc(networking, gLnk("S", "telnet.dbg", "noLinkInserted"))
doc397.iconSrc = ICONPATH + "fileok.gif"
doc398 = insDoc(networking, gLnk("S", "telnetd.dbg", "noLinkInserted"))
doc398.iconSrc = ICONPATH + "fileok.gif"
doc399 = insDoc(networking, gLnk("S", "tftp.dbg", "noLinkInserted"))
doc399.iconSrc = ICONPATH + "fileok.gif"
doc400 = insDoc(networking, gLnk("S", "traceroute.dbg", "noLinkInserted"))
doc400.iconSrc = ICONPATH + "fileok.gif"
doc401 = insDoc(networking, gLnk("S", "tunctl.dbg", "noLinkInserted"))
doc401.iconSrc = ICONPATH + "fileok.gif"
udhcp = insFld(networking, gFld("udhcp", ""))
udhcp.iconSrc = ICONPATH + "folderopenok.gif"
udhcp.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc402 = insDoc(udhcp, gLnk("S", "arpping.dbg", "noLinkInserted"))
doc402.iconSrc = ICONPATH + "fileok.gif"
doc403 = insDoc(udhcp, gLnk("S", "common.dbg", "noLinkInserted"))
doc403.iconSrc = ICONPATH + "fileok.gif"
doc404 = insDoc(udhcp, gLnk("S", "dhcpc.dbg", "noLinkInserted"))
doc404.iconSrc = ICONPATH + "fileok.gif"
doc405 = insDoc(udhcp, gLnk("S", "dhcpd.dbg", "noLinkInserted"))
doc405.iconSrc = ICONPATH + "fileok.gif"
doc406 = insDoc(udhcp, gLnk("S", "dhcprelay.dbg", "noLinkInserted"))
doc406.iconSrc = ICONPATH + "fileok.gif"
doc407 = insDoc(udhcp, gLnk("S", "domain_codec.dbg", "noLinkInserted"))
doc407.iconSrc = ICONPATH + "fileok.gif"
doc408 = insDoc(udhcp, gLnk("S", "dumpleases.dbg", "noLinkInserted"))
doc408.iconSrc = ICONPATH + "fileok.gif"
doc409 = insDoc(udhcp, gLnk("S", "files.dbg", "noLinkInserted"))
doc409.iconSrc = ICONPATH + "fileok.gif"
doc410 = insDoc(udhcp, gLnk("S", "leases.dbg", "noLinkInserted"))
doc410.iconSrc = ICONPATH + "fileok.gif"
doc411 = insDoc(udhcp, gLnk("S", "packet.dbg", "noLinkInserted"))
doc411.iconSrc = ICONPATH + "fileok.gif"
doc412 = insDoc(udhcp, gLnk("S", "signalpipe.dbg", "noLinkInserted"))
doc412.iconSrc = ICONPATH + "fileok.gif"
doc413 = insDoc(udhcp, gLnk("S", "socket.dbg", "noLinkInserted"))
doc413.iconSrc = ICONPATH + "fileok.gif"
doc414 = insDoc(udhcp, gLnk("S", "static_leases.dbg", "noLinkInserted"))
doc414.iconSrc = ICONPATH + "fileok.gif"
doc415 = insDoc(networking, gLnk("S", "vconfig.dbg", "noLinkInserted"))
doc415.iconSrc = ICONPATH + "fileok.gif"
doc416 = insDoc(networking, gLnk("S", "wget.dbg", "noLinkInserted"))
doc416.iconSrc = ICONPATH + "filefail.gif"
doc417 = insDoc(networking, gLnk("S", "zcip.dbg", "noLinkInserted"))
doc417.iconSrc = ICONPATH + "fileok.gif"
printutils = insFld(foldersTree, gFld("printutils", ""))
printutils.iconSrc = ICONPATH + "folderopenfail.gif"
printutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc418 = insDoc(printutils, gLnk("S", "lpd.dbg", "noLinkInserted"))
doc418.iconSrc = ICONPATH + "filefail.gif"
doc419 = insDoc(printutils, gLnk("S", "lpr.dbg", "noLinkInserted"))
doc419.iconSrc = ICONPATH + "fileok.gif"
procps = insFld(foldersTree, gFld("procps", ""))
procps.iconSrc = ICONPATH + "folderopenfail.gif"
procps.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc420 = insDoc(procps, gLnk("S", "free.dbg", "noLinkInserted"))
doc420.iconSrc = ICONPATH + "fileok.gif"
doc421 = insDoc(procps, gLnk("S", "fuser.dbg", "noLinkInserted"))
doc421.iconSrc = ICONPATH + "fileok.gif"
doc422 = insDoc(procps, gLnk("S", "iostat.dbg", "noLinkInserted"))
doc422.iconSrc = ICONPATH + "fileok.gif"
doc423 = insDoc(procps, gLnk("S", "kill.dbg", "noLinkInserted"))
doc423.iconSrc = ICONPATH + "fileok.gif"
doc424 = insDoc(procps, gLnk("S", "mpstat.dbg", "noLinkInserted"))
doc424.iconSrc = ICONPATH + "fileok.gif"
doc425 = insDoc(procps, gLnk("S", "nmeter.dbg", "noLinkInserted"))
doc425.iconSrc = ICONPATH + "fileok.gif"
doc426 = insDoc(procps, gLnk("S", "pgrep.dbg", "noLinkInserted"))
doc426.iconSrc = ICONPATH + "fileok.gif"
doc427 = insDoc(procps, gLnk("S", "pidof.dbg", "noLinkInserted"))
doc427.iconSrc = ICONPATH + "fileok.gif"
doc428 = insDoc(procps, gLnk("S", "pmap.dbg", "noLinkInserted"))
doc428.iconSrc = ICONPATH + "fileok.gif"
doc429 = insDoc(procps, gLnk("S", "powertop.dbg", "noLinkInserted"))
doc429.iconSrc = ICONPATH + "filefail.gif"
doc430 = insDoc(procps, gLnk("S", "ps.dbg", "noLinkInserted"))
doc430.iconSrc = ICONPATH + "fileok.gif"
doc431 = insDoc(procps, gLnk("S", "renice.dbg", "noLinkInserted"))
doc431.iconSrc = ICONPATH + "fileok.gif"
doc432 = insDoc(procps, gLnk("S", "smemcap.dbg", "noLinkInserted"))
doc432.iconSrc = ICONPATH + "fileok.gif"
doc433 = insDoc(procps, gLnk("S", "sysctl.dbg", "noLinkInserted"))
doc433.iconSrc = ICONPATH + "fileok.gif"
doc434 = insDoc(procps, gLnk("S", "top.dbg", "noLinkInserted"))
doc434.iconSrc = ICONPATH + "filefail.gif"
doc435 = insDoc(procps, gLnk("S", "uptime.dbg", "noLinkInserted"))
doc435.iconSrc = ICONPATH + "fileok.gif"
doc436 = insDoc(procps, gLnk("S", "watch.dbg", "noLinkInserted"))
doc436.iconSrc = ICONPATH + "fileok.gif"
runit = insFld(foldersTree, gFld("runit", ""))
runit.iconSrc = ICONPATH + "folderopenfail.gif"
runit.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc437 = insDoc(runit, gLnk("S", "chpst.dbg", "noLinkInserted"))
doc437.iconSrc = ICONPATH + "fileok.gif"
doc438 = insDoc(runit, gLnk("S", "runsv.dbg", "noLinkInserted"))
doc438.iconSrc = ICONPATH + "fileok.gif"
doc439 = insDoc(runit, gLnk("S", "runsvdir.dbg", "noLinkInserted"))
doc439.iconSrc = ICONPATH + "fileok.gif"
doc440 = insDoc(runit, gLnk("S", "sv.dbg", "noLinkInserted"))
doc440.iconSrc = ICONPATH + "fileok.gif"
doc441 = insDoc(runit, gLnk("S", "svlogd.dbg", "noLinkInserted"))
doc441.iconSrc = ICONPATH + "filefail.gif"
selinux = insFld(foldersTree, gFld("selinux", ""))
selinux.iconSrc = ICONPATH + "folderopenok.gif"
selinux.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc442 = insDoc(selinux, gLnk("S", "chcon.dbg", "noLinkInserted"))
doc442.iconSrc = ICONPATH + "fileok.gif"
doc443 = insDoc(selinux, gLnk("S", "getenforce.dbg", "noLinkInserted"))
doc443.iconSrc = ICONPATH + "fileok.gif"
doc444 = insDoc(selinux, gLnk("S", "getsebool.dbg", "noLinkInserted"))
doc444.iconSrc = ICONPATH + "fileok.gif"
doc445 = insDoc(selinux, gLnk("S", "load_policy.dbg", "noLinkInserted"))
doc445.iconSrc = ICONPATH + "fileok.gif"
doc446 = insDoc(selinux, gLnk("S", "matchpathcon.dbg", "noLinkInserted"))
doc446.iconSrc = ICONPATH + "fileok.gif"
doc447 = insDoc(selinux, gLnk("S", "runcon.dbg", "noLinkInserted"))
doc447.iconSrc = ICONPATH + "fileok.gif"
doc448 = insDoc(selinux, gLnk("S", "selinuxenabled.dbg", "noLinkInserted"))
doc448.iconSrc = ICONPATH + "fileok.gif"
doc449 = insDoc(selinux, gLnk("S", "sestatus.dbg", "noLinkInserted"))
doc449.iconSrc = ICONPATH + "fileok.gif"
doc450 = insDoc(selinux, gLnk("S", "setenforce.dbg", "noLinkInserted"))
doc450.iconSrc = ICONPATH + "fileok.gif"
doc451 = insDoc(selinux, gLnk("S", "setfiles.dbg", "noLinkInserted"))
doc451.iconSrc = ICONPATH + "fileok.gif"
doc452 = insDoc(selinux, gLnk("S", "setsebool.dbg", "noLinkInserted"))
doc452.iconSrc = ICONPATH + "fileok.gif"
shell = insFld(foldersTree, gFld("shell", ""))
shell.iconSrc = ICONPATH + "folderopenfail.gif"
shell.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc453 = insDoc(shell, gLnk("S", "ash.dbg", "noLinkInserted"))
doc453.iconSrc = ICONPATH + "filefail.gif"
doc454 = insDoc(shell, gLnk("S", "ash_ptr_hack.dbg", "noLinkInserted"))
doc454.iconSrc = ICONPATH + "fileok.gif"
doc455 = insDoc(shell, gLnk("S", "cttyhack.dbg", "noLinkInserted"))
doc455.iconSrc = ICONPATH + "fileok.gif"
doc456 = insDoc(shell, gLnk("S", "hush.dbg", "noLinkInserted"))
doc456.iconSrc = ICONPATH + "filefail.gif"
doc457 = insDoc(shell, gLnk("S", "match.dbg", "noLinkInserted"))
doc457.iconSrc = ICONPATH + "fileok.gif"
doc458 = insDoc(shell, gLnk("S", "math.dbg", "noLinkInserted"))
doc458.iconSrc = ICONPATH + "fileok.gif"
doc459 = insDoc(shell, gLnk("S", "random.dbg", "noLinkInserted"))
doc459.iconSrc = ICONPATH + "fileok.gif"
doc460 = insDoc(shell, gLnk("S", "shell_common.dbg", "noLinkInserted"))
doc460.iconSrc = ICONPATH + "fileok.gif"
sysklogd = insFld(foldersTree, gFld("sysklogd", ""))
sysklogd.iconSrc = ICONPATH + "folderopenfail.gif"
sysklogd.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc461 = insDoc(sysklogd, gLnk("S", "klogd.dbg", "noLinkInserted"))
doc461.iconSrc = ICONPATH + "filefail.gif"
doc462 = insDoc(sysklogd, gLnk("S", "logread.dbg", "noLinkInserted"))
doc462.iconSrc = ICONPATH + "fileok.gif"
doc463 = insDoc(sysklogd, gLnk("S", "syslogd_and_logger.dbg", "noLinkInserted"))
doc463.iconSrc = ICONPATH + "filefail.gif"
util_linux = insFld(foldersTree, gFld("util-linux", ""))
util_linux.iconSrc = ICONPATH + "folderopenfail.gif"
util_linux.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc464 = insDoc(util_linux, gLnk("S", "acpid.dbg", "noLinkInserted"))
doc464.iconSrc = ICONPATH + "fileok.gif"
doc465 = insDoc(util_linux, gLnk("S", "blkid.dbg", "noLinkInserted"))
doc465.iconSrc = ICONPATH + "fileok.gif"
doc466 = insDoc(util_linux, gLnk("S", "blockdev.dbg", "noLinkInserted"))
doc466.iconSrc = ICONPATH + "fileok.gif"
doc467 = insDoc(util_linux, gLnk("S", "dmesg.dbg", "noLinkInserted"))
doc467.iconSrc = ICONPATH + "fileok.gif"
doc468 = insDoc(util_linux, gLnk("S", "fbset.dbg", "noLinkInserted"))
doc468.iconSrc = ICONPATH + "fileok.gif"
doc469 = insDoc(util_linux, gLnk("S", "fdformat.dbg", "noLinkInserted"))
doc469.iconSrc = ICONPATH + "fileok.gif"
doc470 = insDoc(util_linux, gLnk("S", "fdisk.dbg", "noLinkInserted"))
doc470.iconSrc = ICONPATH + "fileok.gif"
doc471 = insDoc(util_linux, gLnk("S", "findfs.dbg", "noLinkInserted"))
doc471.iconSrc = ICONPATH + "fileok.gif"
doc472 = insDoc(util_linux, gLnk("S", "flock.dbg", "noLinkInserted"))
doc472.iconSrc = ICONPATH + "fileok.gif"
doc473 = insDoc(util_linux, gLnk("S", "freeramdisk.dbg", "noLinkInserted"))
doc473.iconSrc = ICONPATH + "fileok.gif"
doc474 = insDoc(util_linux, gLnk("S", "fsck_minix.dbg", "noLinkInserted"))
doc474.iconSrc = ICONPATH + "fileok.gif"
doc475 = insDoc(util_linux, gLnk("S", "getopt.dbg", "noLinkInserted"))
doc475.iconSrc = ICONPATH + "fileok.gif"
doc476 = insDoc(util_linux, gLnk("S", "hexdump.dbg", "noLinkInserted"))
doc476.iconSrc = ICONPATH + "fileok.gif"
doc477 = insDoc(util_linux, gLnk("S", "hwclock.dbg", "noLinkInserted"))
doc477.iconSrc = ICONPATH + "filefail.gif"
doc478 = insDoc(util_linux, gLnk("S", "ipcrm.dbg", "noLinkInserted"))
doc478.iconSrc = ICONPATH + "fileok.gif"
doc479 = insDoc(util_linux, gLnk("S", "ipcs.dbg", "noLinkInserted"))
doc479.iconSrc = ICONPATH + "fileok.gif"
doc480 = insDoc(util_linux, gLnk("S", "losetup.dbg", "noLinkInserted"))
doc480.iconSrc = ICONPATH + "fileok.gif"
doc481 = insDoc(util_linux, gLnk("S", "lspci.dbg", "noLinkInserted"))
doc481.iconSrc = ICONPATH + "fileok.gif"
doc482 = insDoc(util_linux, gLnk("S", "lsusb.dbg", "noLinkInserted"))
doc482.iconSrc = ICONPATH + "fileok.gif"
doc483 = insDoc(util_linux, gLnk("S", "mdev.dbg", "noLinkInserted"))
doc483.iconSrc = ICONPATH + "filefail.gif"
doc484 = insDoc(util_linux, gLnk("S", "mkfs_ext2.dbg", "noLinkInserted"))
doc484.iconSrc = ICONPATH + "fileok.gif"
doc485 = insDoc(util_linux, gLnk("S", "mkfs_minix.dbg", "noLinkInserted"))
doc485.iconSrc = ICONPATH + "fileok.gif"
doc486 = insDoc(util_linux, gLnk("S", "mkfs_reiser.dbg", "noLinkInserted"))
doc486.iconSrc = ICONPATH + "fileok.gif"
doc487 = insDoc(util_linux, gLnk("S", "mkfs_vfat.dbg", "noLinkInserted"))
doc487.iconSrc = ICONPATH + "fileok.gif"
doc488 = insDoc(util_linux, gLnk("S", "mkswap.dbg", "noLinkInserted"))
doc488.iconSrc = ICONPATH + "fileok.gif"
doc489 = insDoc(util_linux, gLnk("S", "more.dbg", "noLinkInserted"))
doc489.iconSrc = ICONPATH + "fileok.gif"
doc490 = insDoc(util_linux, gLnk("S", "mount.dbg", "noLinkInserted"))
doc490.iconSrc = ICONPATH + "filefail.gif"
doc491 = insDoc(util_linux, gLnk("S", "pivot_root.dbg", "noLinkInserted"))
doc491.iconSrc = ICONPATH + "fileok.gif"
doc492 = insDoc(util_linux, gLnk("S", "rdate.dbg", "noLinkInserted"))
doc492.iconSrc = ICONPATH + "fileok.gif"
doc493 = insDoc(util_linux, gLnk("S", "rdev.dbg", "noLinkInserted"))
doc493.iconSrc = ICONPATH + "fileok.gif"
doc494 = insDoc(util_linux, gLnk("S", "readprofile.dbg", "noLinkInserted"))
doc494.iconSrc = ICONPATH + "fileok.gif"
doc495 = insDoc(util_linux, gLnk("S", "rev.dbg", "noLinkInserted"))
doc495.iconSrc = ICONPATH + "fileok.gif"
doc496 = insDoc(util_linux, gLnk("S", "rtcwake.dbg", "noLinkInserted"))
doc496.iconSrc = ICONPATH + "fileok.gif"
doc497 = insDoc(util_linux, gLnk("S", "script.dbg", "noLinkInserted"))
doc497.iconSrc = ICONPATH + "fileok.gif"
doc498 = insDoc(util_linux, gLnk("S", "scriptreplay.dbg", "noLinkInserted"))
doc498.iconSrc = ICONPATH + "fileok.gif"
doc499 = insDoc(util_linux, gLnk("S", "setarch.dbg", "noLinkInserted"))
doc499.iconSrc = ICONPATH + "fileok.gif"
doc500 = insDoc(util_linux, gLnk("S", "swaponoff.dbg", "noLinkInserted"))
doc500.iconSrc = ICONPATH + "fileok.gif"
doc501 = insDoc(util_linux, gLnk("S", "switch_root.dbg", "noLinkInserted"))
doc501.iconSrc = ICONPATH + "fileok.gif"
doc502 = insDoc(util_linux, gLnk("S", "umount.dbg", "noLinkInserted"))
doc502.iconSrc = ICONPATH + "fileok.gif"
volume_id = insFld(util_linux, gFld("volume_id", ""))
volume_id.iconSrc = ICONPATH + "folderopenok.gif"
volume_id.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc503 = insDoc(volume_id, gLnk("S", "btrfs.dbg", "noLinkInserted"))
doc503.iconSrc = ICONPATH + "fileok.gif"
doc504 = insDoc(volume_id, gLnk("S", "cramfs.dbg", "noLinkInserted"))
doc504.iconSrc = ICONPATH + "fileok.gif"
doc505 = insDoc(volume_id, gLnk("S", "ext.dbg", "noLinkInserted"))
doc505.iconSrc = ICONPATH + "fileok.gif"
doc506 = insDoc(volume_id, gLnk("S", "fat.dbg", "noLinkInserted"))
doc506.iconSrc = ICONPATH + "fileok.gif"
doc507 = insDoc(volume_id, gLnk("S", "get_devname.dbg", "noLinkInserted"))
doc507.iconSrc = ICONPATH + "fileok.gif"
doc508 = insDoc(volume_id, gLnk("S", "hfs.dbg", "noLinkInserted"))
doc508.iconSrc = ICONPATH + "fileok.gif"
doc509 = insDoc(volume_id, gLnk("S", "iso9660.dbg", "noLinkInserted"))
doc509.iconSrc = ICONPATH + "fileok.gif"
doc510 = insDoc(volume_id, gLnk("S", "jfs.dbg", "noLinkInserted"))
doc510.iconSrc = ICONPATH + "fileok.gif"
doc511 = insDoc(volume_id, gLnk("S", "linux_raid.dbg", "noLinkInserted"))
doc511.iconSrc = ICONPATH + "fileok.gif"
doc512 = insDoc(volume_id, gLnk("S", "linux_swap.dbg", "noLinkInserted"))
doc512.iconSrc = ICONPATH + "fileok.gif"
doc513 = insDoc(volume_id, gLnk("S", "luks.dbg", "noLinkInserted"))
doc513.iconSrc = ICONPATH + "fileok.gif"
doc514 = insDoc(volume_id, gLnk("S", "ntfs.dbg", "noLinkInserted"))
doc514.iconSrc = ICONPATH + "fileok.gif"
doc515 = insDoc(volume_id, gLnk("S", "ocfs2.dbg", "noLinkInserted"))
doc515.iconSrc = ICONPATH + "fileok.gif"
doc516 = insDoc(volume_id, gLnk("S", "reiserfs.dbg", "noLinkInserted"))
doc516.iconSrc = ICONPATH + "fileok.gif"
doc517 = insDoc(volume_id, gLnk("S", "romfs.dbg", "noLinkInserted"))
doc517.iconSrc = ICONPATH + "fileok.gif"
doc518 = insDoc(volume_id, gLnk("S", "sysv.dbg", "noLinkInserted"))
doc518.iconSrc = ICONPATH + "fileok.gif"
doc519 = insDoc(volume_id, gLnk("S", "udf.dbg", "noLinkInserted"))
doc519.iconSrc = ICONPATH + "fileok.gif"
doc520 = insDoc(volume_id, gLnk("S", "util.dbg", "noLinkInserted"))
doc520.iconSrc = ICONPATH + "fileok.gif"
doc521 = insDoc(volume_id, gLnk("S", "volume_id.dbg", "noLinkInserted"))
doc521.iconSrc = ICONPATH + "fileok.gif"
doc522 = insDoc(volume_id, gLnk("S", "xfs.dbg", "noLinkInserted"))
doc522.iconSrc = ICONPATH + "fileok.gif"
