USETEXTLINKS = 1
STARTALLOPEN = 0
ICONPATH = '/~eifx/TypeChefWebInt/php/include/images/treeview/'
foldersTree = gFld("<i>busybox</i>", "")
foldersTree.treeID = "Frameset"
foldersTree.iconSrc = ICONPATH + "folderopenfail.gif"
foldersTree.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
applets = insFld(foldersTree, gFld("applets", ""))
applets.iconSrc = ICONPATH + "folderopenok.gif"
applets.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc0 = insDoc(applets, gLnk("S", "applets - Copy.dbg", "files/busybox/applets/applets_-_Copy.dbg"))
doc0.iconSrc = ICONPATH + "fileok.gif"
doc1 = insDoc(applets, gLnk("S", "applets.dbg", "files/busybox/applets/applets.dbg"))
doc1.iconSrc = ICONPATH + "fileok.gif"
archival = insFld(foldersTree, gFld("archival", ""))
archival.iconSrc = ICONPATH + "folderopenok.gif"
archival.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc2 = insDoc(archival, gLnk("S", "ar.dbg", "files/busybox/archival/ar.dbg"))
doc2.iconSrc = ICONPATH + "fileok.gif"
doc3 = insDoc(archival, gLnk("S", "bbunzip.dbg", "files/busybox/archival/bbunzip.dbg"))
doc3.iconSrc = ICONPATH + "fileok.gif"
doc4 = insDoc(archival, gLnk("S", "bzip2.dbg", "files/busybox/archival/bzip2.dbg"))
doc4.iconSrc = ICONPATH + "fileok.gif"
doc5 = insDoc(archival, gLnk("S", "cpio.dbg", "files/busybox/archival/cpio.dbg"))
doc5.iconSrc = ICONPATH + "fileok.gif"
doc6 = insDoc(archival, gLnk("S", "dpkg.dbg", "files/busybox/archival/dpkg.dbg"))
doc6.iconSrc = ICONPATH + "fileok.gif"
doc7 = insDoc(archival, gLnk("S", "dpkg_deb.dbg", "files/busybox/archival/dpkg_deb.dbg"))
doc7.iconSrc = ICONPATH + "fileok.gif"
doc8 = insDoc(archival, gLnk("S", "gzip.dbg", "files/busybox/archival/gzip.dbg"))
doc8.iconSrc = ICONPATH + "fileok.gif"
libarchive = insFld(archival, gFld("libarchive", ""))
libarchive.iconSrc = ICONPATH + "folderopenok.gif"
libarchive.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc9 = insDoc(libarchive, gLnk("S", "data_align.dbg", "files/busybox/archival/libarchive/data_align.dbg"))
doc9.iconSrc = ICONPATH + "fileok.gif"
doc10 = insDoc(libarchive, gLnk("S", "data_extract_all.dbg", "files/busybox/archival/libarchive/data_extract_all.dbg"))
doc10.iconSrc = ICONPATH + "fileok.gif"
doc11 = insDoc(libarchive, gLnk("S", "data_extract_to_command.dbg", "files/busybox/archival/libarchive/data_extract_to_command.dbg"))
doc11.iconSrc = ICONPATH + "fileok.gif"
doc12 = insDoc(libarchive, gLnk("S", "data_extract_to_stdout.dbg", "files/busybox/archival/libarchive/data_extract_to_stdout.dbg"))
doc12.iconSrc = ICONPATH + "fileok.gif"
doc13 = insDoc(libarchive, gLnk("S", "data_skip.dbg", "files/busybox/archival/libarchive/data_skip.dbg"))
doc13.iconSrc = ICONPATH + "fileok.gif"
doc14 = insDoc(libarchive, gLnk("S", "decompress_bunzip2.dbg", "files/busybox/archival/libarchive/decompress_bunzip2.dbg"))
doc14.iconSrc = ICONPATH + "fileok.gif"
doc15 = insDoc(libarchive, gLnk("S", "decompress_uncompress.dbg", "files/busybox/archival/libarchive/decompress_uncompress.dbg"))
doc15.iconSrc = ICONPATH + "fileok.gif"
doc16 = insDoc(libarchive, gLnk("S", "decompress_unlzma.dbg", "files/busybox/archival/libarchive/decompress_unlzma.dbg"))
doc16.iconSrc = ICONPATH + "fileok.gif"
doc17 = insDoc(libarchive, gLnk("S", "decompress_unxz.dbg", "files/busybox/archival/libarchive/decompress_unxz.dbg"))
doc17.iconSrc = ICONPATH + "fileok.gif"
doc18 = insDoc(libarchive, gLnk("S", "decompress_unzip.dbg", "files/busybox/archival/libarchive/decompress_unzip.dbg"))
doc18.iconSrc = ICONPATH + "fileok.gif"
doc19 = insDoc(libarchive, gLnk("S", "filter_accept_all.dbg", "files/busybox/archival/libarchive/filter_accept_all.dbg"))
doc19.iconSrc = ICONPATH + "fileok.gif"
doc20 = insDoc(libarchive, gLnk("S", "filter_accept_list.dbg", "files/busybox/archival/libarchive/filter_accept_list.dbg"))
doc20.iconSrc = ICONPATH + "fileok.gif"
doc21 = insDoc(libarchive, gLnk("S", "filter_accept_list_reassign.dbg", "files/busybox/archival/libarchive/filter_accept_list_reassign.dbg"))
doc21.iconSrc = ICONPATH + "fileok.gif"
doc22 = insDoc(libarchive, gLnk("S", "filter_accept_reject_list.dbg", "files/busybox/archival/libarchive/filter_accept_reject_list.dbg"))
doc22.iconSrc = ICONPATH + "fileok.gif"
doc23 = insDoc(libarchive, gLnk("S", "find_list_entry.dbg", "files/busybox/archival/libarchive/find_list_entry.dbg"))
doc23.iconSrc = ICONPATH + "fileok.gif"
doc24 = insDoc(libarchive, gLnk("S", "get_header_ar.dbg", "files/busybox/archival/libarchive/get_header_ar.dbg"))
doc24.iconSrc = ICONPATH + "fileok.gif"
doc25 = insDoc(libarchive, gLnk("S", "get_header_cpio.dbg", "files/busybox/archival/libarchive/get_header_cpio.dbg"))
doc25.iconSrc = ICONPATH + "fileok.gif"
doc26 = insDoc(libarchive, gLnk("S", "get_header_tar.dbg", "files/busybox/archival/libarchive/get_header_tar.dbg"))
doc26.iconSrc = ICONPATH + "fileok.gif"
doc27 = insDoc(libarchive, gLnk("S", "get_header_tar_bz2.dbg", "files/busybox/archival/libarchive/get_header_tar_bz2.dbg"))
doc27.iconSrc = ICONPATH + "fileok.gif"
doc28 = insDoc(libarchive, gLnk("S", "get_header_tar_gz.dbg", "files/busybox/archival/libarchive/get_header_tar_gz.dbg"))
doc28.iconSrc = ICONPATH + "fileok.gif"
doc29 = insDoc(libarchive, gLnk("S", "get_header_tar_lzma.dbg", "files/busybox/archival/libarchive/get_header_tar_lzma.dbg"))
doc29.iconSrc = ICONPATH + "fileok.gif"
doc30 = insDoc(libarchive, gLnk("S", "header_list.dbg", "files/busybox/archival/libarchive/header_list.dbg"))
doc30.iconSrc = ICONPATH + "fileok.gif"
doc31 = insDoc(libarchive, gLnk("S", "header_skip.dbg", "files/busybox/archival/libarchive/header_skip.dbg"))
doc31.iconSrc = ICONPATH + "fileok.gif"
doc32 = insDoc(libarchive, gLnk("S", "header_verbose_list.dbg", "files/busybox/archival/libarchive/header_verbose_list.dbg"))
doc32.iconSrc = ICONPATH + "fileok.gif"
doc33 = insDoc(libarchive, gLnk("S", "init_handle.dbg", "files/busybox/archival/libarchive/init_handle.dbg"))
doc33.iconSrc = ICONPATH + "fileok.gif"
doc34 = insDoc(libarchive, gLnk("S", "lzo1x_1.dbg", "files/busybox/archival/libarchive/lzo1x_1.dbg"))
doc34.iconSrc = ICONPATH + "fileok.gif"
doc35 = insDoc(libarchive, gLnk("S", "lzo1x_1o.dbg", "files/busybox/archival/libarchive/lzo1x_1o.dbg"))
doc35.iconSrc = ICONPATH + "fileok.gif"
doc36 = insDoc(libarchive, gLnk("S", "lzo1x_9x.dbg", "files/busybox/archival/libarchive/lzo1x_9x.dbg"))
doc36.iconSrc = ICONPATH + "fileok.gif"
doc37 = insDoc(libarchive, gLnk("S", "lzo1x_d.dbg", "files/busybox/archival/libarchive/lzo1x_d.dbg"))
doc37.iconSrc = ICONPATH + "fileok.gif"
doc38 = insDoc(libarchive, gLnk("S", "open_transformer.dbg", "files/busybox/archival/libarchive/open_transformer.dbg"))
doc38.iconSrc = ICONPATH + "fileok.gif"
doc39 = insDoc(libarchive, gLnk("S", "seek_by_jump.dbg", "files/busybox/archival/libarchive/seek_by_jump.dbg"))
doc39.iconSrc = ICONPATH + "fileok.gif"
doc40 = insDoc(libarchive, gLnk("S", "seek_by_read.dbg", "files/busybox/archival/libarchive/seek_by_read.dbg"))
doc40.iconSrc = ICONPATH + "fileok.gif"
doc41 = insDoc(libarchive, gLnk("S", "unpack_ar_archive.dbg", "files/busybox/archival/libarchive/unpack_ar_archive.dbg"))
doc41.iconSrc = ICONPATH + "fileok.gif"
doc42 = insDoc(archival, gLnk("S", "lzop.dbg", "files/busybox/archival/lzop.dbg"))
doc42.iconSrc = ICONPATH + "fileok.gif"
doc43 = insDoc(archival, gLnk("S", "rpm.dbg", "files/busybox/archival/rpm.dbg"))
doc43.iconSrc = ICONPATH + "fileok.gif"
doc44 = insDoc(archival, gLnk("S", "rpm2cpio.dbg", "files/busybox/archival/rpm2cpio.dbg"))
doc44.iconSrc = ICONPATH + "fileok.gif"
doc45 = insDoc(archival, gLnk("S", "tar.dbg", "files/busybox/archival/tar.dbg"))
doc45.iconSrc = ICONPATH + "fileok.gif"
doc46 = insDoc(archival, gLnk("S", "unzip.dbg", "files/busybox/archival/unzip.dbg"))
doc46.iconSrc = ICONPATH + "fileok.gif"
console_tools = insFld(foldersTree, gFld("console-tools", ""))
console_tools.iconSrc = ICONPATH + "folderopenok.gif"
console_tools.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc47 = insDoc(console_tools, gLnk("S", "chvt.dbg", "files/busybox/console-tools/chvt.dbg"))
doc47.iconSrc = ICONPATH + "fileok.gif"
doc48 = insDoc(console_tools, gLnk("S", "clear.dbg", "files/busybox/console-tools/clear.dbg"))
doc48.iconSrc = ICONPATH + "fileok.gif"
doc49 = insDoc(console_tools, gLnk("S", "deallocvt.dbg", "files/busybox/console-tools/deallocvt.dbg"))
doc49.iconSrc = ICONPATH + "fileok.gif"
doc50 = insDoc(console_tools, gLnk("S", "dumpkmap.dbg", "files/busybox/console-tools/dumpkmap.dbg"))
doc50.iconSrc = ICONPATH + "fileok.gif"
doc51 = insDoc(console_tools, gLnk("S", "fgconsole.dbg", "files/busybox/console-tools/fgconsole.dbg"))
doc51.iconSrc = ICONPATH + "fileok.gif"
doc52 = insDoc(console_tools, gLnk("S", "kbd_mode.dbg", "files/busybox/console-tools/kbd_mode.dbg"))
doc52.iconSrc = ICONPATH + "fileok.gif"
doc53 = insDoc(console_tools, gLnk("S", "loadfont.dbg", "files/busybox/console-tools/loadfont.dbg"))
doc53.iconSrc = ICONPATH + "fileok.gif"
doc54 = insDoc(console_tools, gLnk("S", "loadkmap.dbg", "files/busybox/console-tools/loadkmap.dbg"))
doc54.iconSrc = ICONPATH + "fileok.gif"
doc55 = insDoc(console_tools, gLnk("S", "openvt.dbg", "files/busybox/console-tools/openvt.dbg"))
doc55.iconSrc = ICONPATH + "fileok.gif"
doc56 = insDoc(console_tools, gLnk("S", "reset.dbg", "files/busybox/console-tools/reset.dbg"))
doc56.iconSrc = ICONPATH + "fileok.gif"
doc57 = insDoc(console_tools, gLnk("S", "resize.dbg", "files/busybox/console-tools/resize.dbg"))
doc57.iconSrc = ICONPATH + "fileok.gif"
doc58 = insDoc(console_tools, gLnk("S", "setconsole.dbg", "files/busybox/console-tools/setconsole.dbg"))
doc58.iconSrc = ICONPATH + "fileok.gif"
doc59 = insDoc(console_tools, gLnk("S", "setkeycodes.dbg", "files/busybox/console-tools/setkeycodes.dbg"))
doc59.iconSrc = ICONPATH + "fileok.gif"
doc60 = insDoc(console_tools, gLnk("S", "setlogcons.dbg", "files/busybox/console-tools/setlogcons.dbg"))
doc60.iconSrc = ICONPATH + "fileok.gif"
doc61 = insDoc(console_tools, gLnk("S", "showkey.dbg", "files/busybox/console-tools/showkey.dbg"))
doc61.iconSrc = ICONPATH + "fileok.gif"
coreutils = insFld(foldersTree, gFld("coreutils", ""))
coreutils.iconSrc = ICONPATH + "folderopenfail.gif"
coreutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc62 = insDoc(coreutils, gLnk("S", "basename.dbg", "files/busybox/coreutils/basename.dbg"))
doc62.iconSrc = ICONPATH + "fileok.gif"
doc63 = insDoc(coreutils, gLnk("S", "cal.dbg", "files/busybox/coreutils/cal.dbg"))
doc63.iconSrc = ICONPATH + "fileok.gif"
doc64 = insDoc(coreutils, gLnk("S", "cat.dbg", "files/busybox/coreutils/cat.dbg"))
doc64.iconSrc = ICONPATH + "fileok.gif"
doc65 = insDoc(coreutils, gLnk("S", "catv.dbg", "files/busybox/coreutils/catv.dbg"))
doc65.iconSrc = ICONPATH + "fileok.gif"
doc66 = insDoc(coreutils, gLnk("S", "chgrp.dbg", "files/busybox/coreutils/chgrp.dbg"))
doc66.iconSrc = ICONPATH + "fileok.gif"
doc67 = insDoc(coreutils, gLnk("S", "chmod.dbg", "files/busybox/coreutils/chmod.dbg"))
doc67.iconSrc = ICONPATH + "fileok.gif"
doc68 = insDoc(coreutils, gLnk("S", "chown.dbg", "files/busybox/coreutils/chown.dbg"))
doc68.iconSrc = ICONPATH + "fileok.gif"
doc69 = insDoc(coreutils, gLnk("S", "chroot.dbg", "files/busybox/coreutils/chroot.dbg"))
doc69.iconSrc = ICONPATH + "fileok.gif"
doc70 = insDoc(coreutils, gLnk("S", "cksum.dbg", "files/busybox/coreutils/cksum.dbg"))
doc70.iconSrc = ICONPATH + "fileok.gif"
doc71 = insDoc(coreutils, gLnk("S", "comm.dbg", "files/busybox/coreutils/comm.dbg"))
doc71.iconSrc = ICONPATH + "fileok.gif"
doc72 = insDoc(coreutils, gLnk("S", "cp.dbg", "files/busybox/coreutils/cp.dbg"))
doc72.iconSrc = ICONPATH + "fileok.gif"
doc73 = insDoc(coreutils, gLnk("S", "cut.dbg", "files/busybox/coreutils/cut.dbg"))
doc73.iconSrc = ICONPATH + "fileok.gif"
doc74 = insDoc(coreutils, gLnk("S", "date.dbg", "files/busybox/coreutils/date.dbg"))
doc74.iconSrc = ICONPATH + "filefail.gif"
doc75 = insDoc(coreutils, gLnk("S", "dd.dbg", "files/busybox/coreutils/dd.dbg"))
doc75.iconSrc = ICONPATH + "fileok.gif"
doc76 = insDoc(coreutils, gLnk("S", "df.dbg", "files/busybox/coreutils/df.dbg"))
doc76.iconSrc = ICONPATH + "fileok.gif"
doc77 = insDoc(coreutils, gLnk("S", "dirname.dbg", "files/busybox/coreutils/dirname.dbg"))
doc77.iconSrc = ICONPATH + "fileok.gif"
doc78 = insDoc(coreutils, gLnk("S", "dos2unix.dbg", "files/busybox/coreutils/dos2unix.dbg"))
doc78.iconSrc = ICONPATH + "fileok.gif"
doc79 = insDoc(coreutils, gLnk("S", "du.dbg", "files/busybox/coreutils/du.dbg"))
doc79.iconSrc = ICONPATH + "fileok.gif"
doc80 = insDoc(coreutils, gLnk("S", "echo.dbg", "files/busybox/coreutils/echo.dbg"))
doc80.iconSrc = ICONPATH + "fileok.gif"
doc81 = insDoc(coreutils, gLnk("S", "env.dbg", "files/busybox/coreutils/env.dbg"))
doc81.iconSrc = ICONPATH + "fileok.gif"
doc82 = insDoc(coreutils, gLnk("S", "expand.dbg", "files/busybox/coreutils/expand.dbg"))
doc82.iconSrc = ICONPATH + "fileok.gif"
doc83 = insDoc(coreutils, gLnk("S", "expr.dbg", "files/busybox/coreutils/expr.dbg"))
doc83.iconSrc = ICONPATH + "fileok.gif"
doc84 = insDoc(coreutils, gLnk("S", "false.dbg", "files/busybox/coreutils/false.dbg"))
doc84.iconSrc = ICONPATH + "fileok.gif"
doc85 = insDoc(coreutils, gLnk("S", "fold.dbg", "files/busybox/coreutils/fold.dbg"))
doc85.iconSrc = ICONPATH + "fileok.gif"
doc86 = insDoc(coreutils, gLnk("S", "fsync.dbg", "files/busybox/coreutils/fsync.dbg"))
doc86.iconSrc = ICONPATH + "fileok.gif"
doc87 = insDoc(coreutils, gLnk("S", "head.dbg", "files/busybox/coreutils/head.dbg"))
doc87.iconSrc = ICONPATH + "fileok.gif"
doc88 = insDoc(coreutils, gLnk("S", "hostid.dbg", "files/busybox/coreutils/hostid.dbg"))
doc88.iconSrc = ICONPATH + "fileok.gif"
doc89 = insDoc(coreutils, gLnk("S", "id.dbg", "files/busybox/coreutils/id.dbg"))
doc89.iconSrc = ICONPATH + "fileok.gif"
doc90 = insDoc(coreutils, gLnk("S", "install.dbg", "files/busybox/coreutils/install.dbg"))
doc90.iconSrc = ICONPATH + "fileok.gif"
doc91 = insDoc(coreutils, gLnk("S", "length.dbg", "files/busybox/coreutils/length.dbg"))
doc91.iconSrc = ICONPATH + "fileok.gif"
libcoreutils = insFld(coreutils, gFld("libcoreutils", ""))
libcoreutils.iconSrc = ICONPATH + "folderopenok.gif"
libcoreutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc92 = insDoc(libcoreutils, gLnk("S", "cp_mv_stat.dbg", "files/busybox/coreutils/libcoreutils/cp_mv_stat.dbg"))
doc92.iconSrc = ICONPATH + "fileok.gif"
doc93 = insDoc(libcoreutils, gLnk("S", "getopt_mk_fifo_nod.dbg", "files/busybox/coreutils/libcoreutils/getopt_mk_fifo_nod.dbg"))
doc93.iconSrc = ICONPATH + "fileok.gif"
doc94 = insDoc(coreutils, gLnk("S", "ln.dbg", "files/busybox/coreutils/ln.dbg"))
doc94.iconSrc = ICONPATH + "fileok.gif"
doc95 = insDoc(coreutils, gLnk("S", "logname.dbg", "files/busybox/coreutils/logname.dbg"))
doc95.iconSrc = ICONPATH + "fileok.gif"
doc96 = insDoc(coreutils, gLnk("S", "ls.dbg", "files/busybox/coreutils/ls.dbg"))
doc96.iconSrc = ICONPATH + "fileok.gif"
doc97 = insDoc(coreutils, gLnk("S", "md5_sha1_sum.dbg", "files/busybox/coreutils/md5_sha1_sum.dbg"))
doc97.iconSrc = ICONPATH + "fileok.gif"
doc98 = insDoc(coreutils, gLnk("S", "mkdir.dbg", "files/busybox/coreutils/mkdir.dbg"))
doc98.iconSrc = ICONPATH + "fileok.gif"
doc99 = insDoc(coreutils, gLnk("S", "mkfifo.dbg", "files/busybox/coreutils/mkfifo.dbg"))
doc99.iconSrc = ICONPATH + "fileok.gif"
doc100 = insDoc(coreutils, gLnk("S", "mknod.dbg", "files/busybox/coreutils/mknod.dbg"))
doc100.iconSrc = ICONPATH + "fileok.gif"
doc101 = insDoc(coreutils, gLnk("S", "mv.dbg", "files/busybox/coreutils/mv.dbg"))
doc101.iconSrc = ICONPATH + "fileok.gif"
doc102 = insDoc(coreutils, gLnk("S", "nice.dbg", "files/busybox/coreutils/nice.dbg"))
doc102.iconSrc = ICONPATH + "fileok.gif"
doc103 = insDoc(coreutils, gLnk("S", "nohup.dbg", "files/busybox/coreutils/nohup.dbg"))
doc103.iconSrc = ICONPATH + "fileok.gif"
doc104 = insDoc(coreutils, gLnk("S", "od.dbg", "files/busybox/coreutils/od.dbg"))
doc104.iconSrc = ICONPATH + "fileok.gif"
doc105 = insDoc(coreutils, gLnk("S", "printenv.dbg", "files/busybox/coreutils/printenv.dbg"))
doc105.iconSrc = ICONPATH + "fileok.gif"
doc106 = insDoc(coreutils, gLnk("S", "printf.dbg", "files/busybox/coreutils/printf.dbg"))
doc106.iconSrc = ICONPATH + "fileok.gif"
doc107 = insDoc(coreutils, gLnk("S", "pwd.dbg", "files/busybox/coreutils/pwd.dbg"))
doc107.iconSrc = ICONPATH + "fileok.gif"
doc108 = insDoc(coreutils, gLnk("S", "readlink.dbg", "files/busybox/coreutils/readlink.dbg"))
doc108.iconSrc = ICONPATH + "fileok.gif"
doc109 = insDoc(coreutils, gLnk("S", "realpath.dbg", "files/busybox/coreutils/realpath.dbg"))
doc109.iconSrc = ICONPATH + "fileok.gif"
doc110 = insDoc(coreutils, gLnk("S", "rm.dbg", "files/busybox/coreutils/rm.dbg"))
doc110.iconSrc = ICONPATH + "fileok.gif"
doc111 = insDoc(coreutils, gLnk("S", "rmdir.dbg", "files/busybox/coreutils/rmdir.dbg"))
doc111.iconSrc = ICONPATH + "fileok.gif"
doc112 = insDoc(coreutils, gLnk("S", "seq.dbg", "files/busybox/coreutils/seq.dbg"))
doc112.iconSrc = ICONPATH + "filefail.gif"
doc113 = insDoc(coreutils, gLnk("S", "sleep.dbg", "files/busybox/coreutils/sleep.dbg"))
doc113.iconSrc = ICONPATH + "fileok.gif"
doc114 = insDoc(coreutils, gLnk("S", "sort.dbg", "files/busybox/coreutils/sort.dbg"))
doc114.iconSrc = ICONPATH + "filefail.gif"
doc115 = insDoc(coreutils, gLnk("S", "split.dbg", "files/busybox/coreutils/split.dbg"))
doc115.iconSrc = ICONPATH + "fileok.gif"
doc116 = insDoc(coreutils, gLnk("S", "stat.dbg", "files/busybox/coreutils/stat.dbg"))
doc116.iconSrc = ICONPATH + "fileok.gif"
doc117 = insDoc(coreutils, gLnk("S", "stty.dbg", "files/busybox/coreutils/stty.dbg"))
doc117.iconSrc = ICONPATH + "fileok.gif"
doc118 = insDoc(coreutils, gLnk("S", "sum.dbg", "files/busybox/coreutils/sum.dbg"))
doc118.iconSrc = ICONPATH + "fileok.gif"
doc119 = insDoc(coreutils, gLnk("S", "sync.dbg", "files/busybox/coreutils/sync.dbg"))
doc119.iconSrc = ICONPATH + "fileok.gif"
doc120 = insDoc(coreutils, gLnk("S", "tac.dbg", "files/busybox/coreutils/tac.dbg"))
doc120.iconSrc = ICONPATH + "fileok.gif"
doc121 = insDoc(coreutils, gLnk("S", "tail.dbg", "files/busybox/coreutils/tail.dbg"))
doc121.iconSrc = ICONPATH + "fileok.gif"
doc122 = insDoc(coreutils, gLnk("S", "tee.dbg", "files/busybox/coreutils/tee.dbg"))
doc122.iconSrc = ICONPATH + "fileok.gif"
doc123 = insDoc(coreutils, gLnk("S", "test.dbg", "files/busybox/coreutils/test.dbg"))
doc123.iconSrc = ICONPATH + "fileok.gif"
doc124 = insDoc(coreutils, gLnk("S", "test_ptr_hack.dbg", "files/busybox/coreutils/test_ptr_hack.dbg"))
doc124.iconSrc = ICONPATH + "fileok.gif"
doc125 = insDoc(coreutils, gLnk("S", "touch.dbg", "files/busybox/coreutils/touch.dbg"))
doc125.iconSrc = ICONPATH + "fileok.gif"
doc126 = insDoc(coreutils, gLnk("S", "tr.dbg", "files/busybox/coreutils/tr.dbg"))
doc126.iconSrc = ICONPATH + "fileok.gif"
doc127 = insDoc(coreutils, gLnk("S", "true.dbg", "files/busybox/coreutils/true.dbg"))
doc127.iconSrc = ICONPATH + "fileok.gif"
doc128 = insDoc(coreutils, gLnk("S", "tty.dbg", "files/busybox/coreutils/tty.dbg"))
doc128.iconSrc = ICONPATH + "fileok.gif"
doc129 = insDoc(coreutils, gLnk("S", "uname.dbg", "files/busybox/coreutils/uname.dbg"))
doc129.iconSrc = ICONPATH + "fileok.gif"
doc130 = insDoc(coreutils, gLnk("S", "uniq.dbg", "files/busybox/coreutils/uniq.dbg"))
doc130.iconSrc = ICONPATH + "fileok.gif"
doc131 = insDoc(coreutils, gLnk("S", "usleep.dbg", "files/busybox/coreutils/usleep.dbg"))
doc131.iconSrc = ICONPATH + "fileok.gif"
doc132 = insDoc(coreutils, gLnk("S", "uudecode.dbg", "files/busybox/coreutils/uudecode.dbg"))
doc132.iconSrc = ICONPATH + "fileok.gif"
doc133 = insDoc(coreutils, gLnk("S", "uuencode.dbg", "files/busybox/coreutils/uuencode.dbg"))
doc133.iconSrc = ICONPATH + "fileok.gif"
doc134 = insDoc(coreutils, gLnk("S", "wc.dbg", "files/busybox/coreutils/wc.dbg"))
doc134.iconSrc = ICONPATH + "fileok.gif"
doc135 = insDoc(coreutils, gLnk("S", "who.dbg", "files/busybox/coreutils/who.dbg"))
doc135.iconSrc = ICONPATH + "fileok.gif"
doc136 = insDoc(coreutils, gLnk("S", "whoami.dbg", "files/busybox/coreutils/whoami.dbg"))
doc136.iconSrc = ICONPATH + "fileok.gif"
doc137 = insDoc(coreutils, gLnk("S", "yes.dbg", "files/busybox/coreutils/yes.dbg"))
doc137.iconSrc = ICONPATH + "fileok.gif"
debianutils = insFld(foldersTree, gFld("debianutils", ""))
debianutils.iconSrc = ICONPATH + "folderopenok.gif"
debianutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc138 = insDoc(debianutils, gLnk("S", "mktemp.dbg", "files/busybox/debianutils/mktemp.dbg"))
doc138.iconSrc = ICONPATH + "fileok.gif"
doc139 = insDoc(debianutils, gLnk("S", "pipe_progress.dbg", "files/busybox/debianutils/pipe_progress.dbg"))
doc139.iconSrc = ICONPATH + "fileok.gif"
doc140 = insDoc(debianutils, gLnk("S", "run_parts.dbg", "files/busybox/debianutils/run_parts.dbg"))
doc140.iconSrc = ICONPATH + "fileok.gif"
doc141 = insDoc(debianutils, gLnk("S", "start_stop_daemon.dbg", "files/busybox/debianutils/start_stop_daemon.dbg"))
doc141.iconSrc = ICONPATH + "fileok.gif"
doc142 = insDoc(debianutils, gLnk("S", "which.dbg", "files/busybox/debianutils/which.dbg"))
doc142.iconSrc = ICONPATH + "fileok.gif"
e2fsprogs = insFld(foldersTree, gFld("e2fsprogs", ""))
e2fsprogs.iconSrc = ICONPATH + "folderopenok.gif"
e2fsprogs.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc143 = insDoc(e2fsprogs, gLnk("S", "chattr.dbg", "files/busybox/e2fsprogs/chattr.dbg"))
doc143.iconSrc = ICONPATH + "fileok.gif"
doc144 = insDoc(e2fsprogs, gLnk("S", "e2fs_lib.dbg", "files/busybox/e2fsprogs/e2fs_lib.dbg"))
doc144.iconSrc = ICONPATH + "fileok.gif"
doc145 = insDoc(e2fsprogs, gLnk("S", "fsck.dbg", "files/busybox/e2fsprogs/fsck.dbg"))
doc145.iconSrc = ICONPATH + "fileok.gif"
doc146 = insDoc(e2fsprogs, gLnk("S", "lsattr.dbg", "files/busybox/e2fsprogs/lsattr.dbg"))
doc146.iconSrc = ICONPATH + "fileok.gif"
doc147 = insDoc(e2fsprogs, gLnk("S", "tune2fs.dbg", "files/busybox/e2fsprogs/tune2fs.dbg"))
doc147.iconSrc = ICONPATH + "fileok.gif"
editors = insFld(foldersTree, gFld("editors", ""))
editors.iconSrc = ICONPATH + "folderopenfail.gif"
editors.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc148 = insDoc(editors, gLnk("S", "awk.dbg", "files/busybox/editors/awk.dbg"))
doc148.iconSrc = ICONPATH + "fileok.gif"
doc149 = insDoc(editors, gLnk("S", "cmp.dbg", "files/busybox/editors/cmp.dbg"))
doc149.iconSrc = ICONPATH + "fileok.gif"
doc150 = insDoc(editors, gLnk("S", "diff.dbg", "files/busybox/editors/diff.dbg"))
doc150.iconSrc = ICONPATH + "fileok.gif"
doc151 = insDoc(editors, gLnk("S", "ed.dbg", "files/busybox/editors/ed.dbg"))
doc151.iconSrc = ICONPATH + "fileok.gif"
doc152 = insDoc(editors, gLnk("S", "patch.dbg", "files/busybox/editors/patch.dbg"))
doc152.iconSrc = ICONPATH + "fileok.gif"
doc153 = insDoc(editors, gLnk("S", "sed.dbg", "files/busybox/editors/sed.dbg"))
doc153.iconSrc = ICONPATH + "fileok.gif"
doc154 = insDoc(editors, gLnk("S", "vi.dbg", "files/busybox/editors/vi.dbg"))
doc154.iconSrc = ICONPATH + "filefail.gif"
findutils = insFld(foldersTree, gFld("findutils", ""))
findutils.iconSrc = ICONPATH + "folderopenfail.gif"
findutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc155 = insDoc(findutils, gLnk("S", "find.dbg", "files/busybox/findutils/find.dbg"))
doc155.iconSrc = ICONPATH + "fileok.gif"
doc156 = insDoc(findutils, gLnk("S", "grep.dbg", "files/busybox/findutils/grep.dbg"))
doc156.iconSrc = ICONPATH + "filefail.gif"
doc157 = insDoc(findutils, gLnk("S", "xargs.dbg", "files/busybox/findutils/xargs.dbg"))
doc157.iconSrc = ICONPATH + "fileok.gif"
init = insFld(foldersTree, gFld("init", ""))
init.iconSrc = ICONPATH + "folderopenfail.gif"
init.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc158 = insDoc(init, gLnk("S", "bootchartd.dbg", "files/busybox/init/bootchartd.dbg"))
doc158.iconSrc = ICONPATH + "filefail.gif"
doc159 = insDoc(init, gLnk("S", "halt.dbg", "files/busybox/init/halt.dbg"))
doc159.iconSrc = ICONPATH + "fileok.gif"
doc160 = insDoc(init, gLnk("S", "init.dbg", "files/busybox/init/init.dbg"))
doc160.iconSrc = ICONPATH + "fileok.gif"
doc161 = insDoc(init, gLnk("S", "mesg.dbg", "files/busybox/init/mesg.dbg"))
doc161.iconSrc = ICONPATH + "fileok.gif"
libbb = insFld(foldersTree, gFld("libbb", ""))
libbb.iconSrc = ICONPATH + "folderopenfail.gif"
libbb.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc162 = insDoc(libbb, gLnk("S", "appletlib.dbg", "files/busybox/libbb/appletlib.dbg"))
doc162.iconSrc = ICONPATH + "filefail.gif"
doc163 = insDoc(libbb, gLnk("S", "ask_confirmation.dbg", "files/busybox/libbb/ask_confirmation.dbg"))
doc163.iconSrc = ICONPATH + "fileok.gif"
doc164 = insDoc(libbb, gLnk("S", "bb_askpass.dbg", "files/busybox/libbb/bb_askpass.dbg"))
doc164.iconSrc = ICONPATH + "fileok.gif"
doc165 = insDoc(libbb, gLnk("S", "bb_basename.dbg", "files/busybox/libbb/bb_basename.dbg"))
doc165.iconSrc = ICONPATH + "fileok.gif"
doc166 = insDoc(libbb, gLnk("S", "bb_bswap_64.dbg", "files/busybox/libbb/bb_bswap_64.dbg"))
doc166.iconSrc = ICONPATH + "fileok.gif"
doc167 = insDoc(libbb, gLnk("S", "bb_do_delay.dbg", "files/busybox/libbb/bb_do_delay.dbg"))
doc167.iconSrc = ICONPATH + "fileok.gif"
doc168 = insDoc(libbb, gLnk("S", "bb_pwd.dbg", "files/busybox/libbb/bb_pwd.dbg"))
doc168.iconSrc = ICONPATH + "fileok.gif"
doc169 = insDoc(libbb, gLnk("S", "bb_qsort.dbg", "files/busybox/libbb/bb_qsort.dbg"))
doc169.iconSrc = ICONPATH + "fileok.gif"
doc170 = insDoc(libbb, gLnk("S", "bb_strtonum.dbg", "files/busybox/libbb/bb_strtonum.dbg"))
doc170.iconSrc = ICONPATH + "fileok.gif"
doc171 = insDoc(libbb, gLnk("S", "change_identity.dbg", "files/busybox/libbb/change_identity.dbg"))
doc171.iconSrc = ICONPATH + "fileok.gif"
doc172 = insDoc(libbb, gLnk("S", "chomp.dbg", "files/busybox/libbb/chomp.dbg"))
doc172.iconSrc = ICONPATH + "fileok.gif"
doc173 = insDoc(libbb, gLnk("S", "compare_string_array.dbg", "files/busybox/libbb/compare_string_array.dbg"))
doc173.iconSrc = ICONPATH + "fileok.gif"
doc174 = insDoc(libbb, gLnk("S", "concat_path_file.dbg", "files/busybox/libbb/concat_path_file.dbg"))
doc174.iconSrc = ICONPATH + "fileok.gif"
doc175 = insDoc(libbb, gLnk("S", "concat_subpath_file.dbg", "files/busybox/libbb/concat_subpath_file.dbg"))
doc175.iconSrc = ICONPATH + "fileok.gif"
doc176 = insDoc(libbb, gLnk("S", "copy_file.dbg", "files/busybox/libbb/copy_file.dbg"))
doc176.iconSrc = ICONPATH + "fileok.gif"
doc177 = insDoc(libbb, gLnk("S", "copyfd.dbg", "files/busybox/libbb/copyfd.dbg"))
doc177.iconSrc = ICONPATH + "fileok.gif"
doc178 = insDoc(libbb, gLnk("S", "correct_password.dbg", "files/busybox/libbb/correct_password.dbg"))
doc178.iconSrc = ICONPATH + "fileok.gif"
doc179 = insDoc(libbb, gLnk("S", "crc32.dbg", "files/busybox/libbb/crc32.dbg"))
doc179.iconSrc = ICONPATH + "fileok.gif"
doc180 = insDoc(libbb, gLnk("S", "create_icmp6_socket.dbg", "files/busybox/libbb/create_icmp6_socket.dbg"))
doc180.iconSrc = ICONPATH + "fileok.gif"
doc181 = insDoc(libbb, gLnk("S", "create_icmp_socket.dbg", "files/busybox/libbb/create_icmp_socket.dbg"))
doc181.iconSrc = ICONPATH + "fileok.gif"
doc182 = insDoc(libbb, gLnk("S", "default_error_retval.dbg", "files/busybox/libbb/default_error_retval.dbg"))
doc182.iconSrc = ICONPATH + "fileok.gif"
doc183 = insDoc(libbb, gLnk("S", "device_open.dbg", "files/busybox/libbb/device_open.dbg"))
doc183.iconSrc = ICONPATH + "fileok.gif"
doc184 = insDoc(libbb, gLnk("S", "die_if_bad_username.dbg", "files/busybox/libbb/die_if_bad_username.dbg"))
doc184.iconSrc = ICONPATH + "fileok.gif"
doc185 = insDoc(libbb, gLnk("S", "dump.dbg", "files/busybox/libbb/dump.dbg"))
doc185.iconSrc = ICONPATH + "fileok.gif"
doc186 = insDoc(libbb, gLnk("S", "execable.dbg", "files/busybox/libbb/execable.dbg"))
doc186.iconSrc = ICONPATH + "fileok.gif"
doc187 = insDoc(libbb, gLnk("S", "fclose_nonstdin.dbg", "files/busybox/libbb/fclose_nonstdin.dbg"))
doc187.iconSrc = ICONPATH + "fileok.gif"
doc188 = insDoc(libbb, gLnk("S", "fflush_stdout_and_exit.dbg", "files/busybox/libbb/fflush_stdout_and_exit.dbg"))
doc188.iconSrc = ICONPATH + "fileok.gif"
doc189 = insDoc(libbb, gLnk("S", "fgets_str.dbg", "files/busybox/libbb/fgets_str.dbg"))
doc189.iconSrc = ICONPATH + "fileok.gif"
doc190 = insDoc(libbb, gLnk("S", "find_mount_point.dbg", "files/busybox/libbb/find_mount_point.dbg"))
doc190.iconSrc = ICONPATH + "fileok.gif"
doc191 = insDoc(libbb, gLnk("S", "find_pid_by_name.dbg", "files/busybox/libbb/find_pid_by_name.dbg"))
doc191.iconSrc = ICONPATH + "fileok.gif"
doc192 = insDoc(libbb, gLnk("S", "find_root_device.dbg", "files/busybox/libbb/find_root_device.dbg"))
doc192.iconSrc = ICONPATH + "fileok.gif"
doc193 = insDoc(libbb, gLnk("S", "full_write.dbg", "files/busybox/libbb/full_write.dbg"))
doc193.iconSrc = ICONPATH + "fileok.gif"
doc194 = insDoc(libbb, gLnk("S", "get_console.dbg", "files/busybox/libbb/get_console.dbg"))
doc194.iconSrc = ICONPATH + "fileok.gif"
doc195 = insDoc(libbb, gLnk("S", "get_cpu_count.dbg", "files/busybox/libbb/get_cpu_count.dbg"))
doc195.iconSrc = ICONPATH + "fileok.gif"
doc196 = insDoc(libbb, gLnk("S", "get_last_path_component.dbg", "files/busybox/libbb/get_last_path_component.dbg"))
doc196.iconSrc = ICONPATH + "fileok.gif"
doc197 = insDoc(libbb, gLnk("S", "get_line_from_file.dbg", "files/busybox/libbb/get_line_from_file.dbg"))
doc197.iconSrc = ICONPATH + "fileok.gif"
doc198 = insDoc(libbb, gLnk("S", "get_volsize.dbg", "files/busybox/libbb/get_volsize.dbg"))
doc198.iconSrc = ICONPATH + "fileok.gif"
doc199 = insDoc(libbb, gLnk("S", "getopt32.dbg", "files/busybox/libbb/getopt32.dbg"))
doc199.iconSrc = ICONPATH + "fileok.gif"
doc200 = insDoc(libbb, gLnk("S", "getpty.dbg", "files/busybox/libbb/getpty.dbg"))
doc200.iconSrc = ICONPATH + "filefail.gif"
doc201 = insDoc(libbb, gLnk("S", "hash_md5_sha.dbg", "files/busybox/libbb/hash_md5_sha.dbg"))
doc201.iconSrc = ICONPATH + "fileok.gif"
doc202 = insDoc(libbb, gLnk("S", "herror_msg.dbg", "files/busybox/libbb/herror_msg.dbg"))
doc202.iconSrc = ICONPATH + "fileok.gif"
doc203 = insDoc(libbb, gLnk("S", "human_readable.dbg", "files/busybox/libbb/human_readable.dbg"))
doc203.iconSrc = ICONPATH + "fileok.gif"
doc204 = insDoc(libbb, gLnk("S", "inet_common.dbg", "files/busybox/libbb/inet_common.dbg"))
doc204.iconSrc = ICONPATH + "fileok.gif"
doc205 = insDoc(libbb, gLnk("S", "info_msg.dbg", "files/busybox/libbb/info_msg.dbg"))
doc205.iconSrc = ICONPATH + "filefail.gif"
doc206 = insDoc(libbb, gLnk("S", "inode_hash.dbg", "files/busybox/libbb/inode_hash.dbg"))
doc206.iconSrc = ICONPATH + "fileok.gif"
doc207 = insDoc(libbb, gLnk("S", "isdirectory.dbg", "files/busybox/libbb/isdirectory.dbg"))
doc207.iconSrc = ICONPATH + "fileok.gif"
doc208 = insDoc(libbb, gLnk("S", "kernel_version.dbg", "files/busybox/libbb/kernel_version.dbg"))
doc208.iconSrc = ICONPATH + "fileok.gif"
doc209 = insDoc(libbb, gLnk("S", "last_char_is.dbg", "files/busybox/libbb/last_char_is.dbg"))
doc209.iconSrc = ICONPATH + "fileok.gif"
doc210 = insDoc(libbb, gLnk("S", "lineedit.dbg", "files/busybox/libbb/lineedit.dbg"))
doc210.iconSrc = ICONPATH + "filefail.gif"
doc211 = insDoc(libbb, gLnk("S", "lineedit_ptr_hack.dbg", "files/busybox/libbb/lineedit_ptr_hack.dbg"))
doc211.iconSrc = ICONPATH + "fileok.gif"
doc212 = insDoc(libbb, gLnk("S", "llist.dbg", "files/busybox/libbb/llist.dbg"))
doc212.iconSrc = ICONPATH + "fileok.gif"
doc213 = insDoc(libbb, gLnk("S", "login.dbg", "files/busybox/libbb/login.dbg"))
doc213.iconSrc = ICONPATH + "filefail.gif"
doc214 = insDoc(libbb, gLnk("S", "loop.dbg", "files/busybox/libbb/loop.dbg"))
doc214.iconSrc = ICONPATH + "fileok.gif"
doc215 = insDoc(libbb, gLnk("S", "make_directory.dbg", "files/busybox/libbb/make_directory.dbg"))
doc215.iconSrc = ICONPATH + "fileok.gif"
doc216 = insDoc(libbb, gLnk("S", "makedev.dbg", "files/busybox/libbb/makedev.dbg"))
doc216.iconSrc = ICONPATH + "fileok.gif"
doc217 = insDoc(libbb, gLnk("S", "match_fstype.dbg", "files/busybox/libbb/match_fstype.dbg"))
doc217.iconSrc = ICONPATH + "fileok.gif"
doc218 = insDoc(libbb, gLnk("S", "messages.dbg", "files/busybox/libbb/messages.dbg"))
doc218.iconSrc = ICONPATH + "fileok.gif"
doc219 = insDoc(libbb, gLnk("S", "mode_string.dbg", "files/busybox/libbb/mode_string.dbg"))
doc219.iconSrc = ICONPATH + "fileok.gif"
doc220 = insDoc(libbb, gLnk("S", "mtab.dbg", "files/busybox/libbb/mtab.dbg"))
doc220.iconSrc = ICONPATH + "fileok.gif"
doc221 = insDoc(libbb, gLnk("S", "obscure.dbg", "files/busybox/libbb/obscure.dbg"))
doc221.iconSrc = ICONPATH + "filefail.gif"
doc222 = insDoc(libbb, gLnk("S", "parse_config.dbg", "files/busybox/libbb/parse_config.dbg"))
doc222.iconSrc = ICONPATH + "filefail.gif"
doc223 = insDoc(libbb, gLnk("S", "parse_mode.dbg", "files/busybox/libbb/parse_mode.dbg"))
doc223.iconSrc = ICONPATH + "fileok.gif"
doc224 = insDoc(libbb, gLnk("S", "perror_msg.dbg", "files/busybox/libbb/perror_msg.dbg"))
doc224.iconSrc = ICONPATH + "fileok.gif"
doc225 = insDoc(libbb, gLnk("S", "perror_nomsg.dbg", "files/busybox/libbb/perror_nomsg.dbg"))
doc225.iconSrc = ICONPATH + "fileok.gif"
doc226 = insDoc(libbb, gLnk("S", "perror_nomsg_and_die.dbg", "files/busybox/libbb/perror_nomsg_and_die.dbg"))
doc226.iconSrc = ICONPATH + "fileok.gif"
doc227 = insDoc(libbb, gLnk("S", "pidfile.dbg", "files/busybox/libbb/pidfile.dbg"))
doc227.iconSrc = ICONPATH + "fileok.gif"
doc228 = insDoc(libbb, gLnk("S", "platform.dbg", "files/busybox/libbb/platform.dbg"))
doc228.iconSrc = ICONPATH + "fileok.gif"
doc229 = insDoc(libbb, gLnk("S", "print_flags.dbg", "files/busybox/libbb/print_flags.dbg"))
doc229.iconSrc = ICONPATH + "fileok.gif"
doc230 = insDoc(libbb, gLnk("S", "printable.dbg", "files/busybox/libbb/printable.dbg"))
doc230.iconSrc = ICONPATH + "fileok.gif"
doc231 = insDoc(libbb, gLnk("S", "printable_string.dbg", "files/busybox/libbb/printable_string.dbg"))
doc231.iconSrc = ICONPATH + "fileok.gif"
doc232 = insDoc(libbb, gLnk("S", "process_escape_sequence.dbg", "files/busybox/libbb/process_escape_sequence.dbg"))
doc232.iconSrc = ICONPATH + "fileok.gif"
doc233 = insDoc(libbb, gLnk("S", "procps.dbg", "files/busybox/libbb/procps.dbg"))
doc233.iconSrc = ICONPATH + "fileok.gif"
doc234 = insDoc(libbb, gLnk("S", "progress.dbg", "files/busybox/libbb/progress.dbg"))
doc234.iconSrc = ICONPATH + "fileok.gif"
doc235 = insDoc(libbb, gLnk("S", "ptr_to_globals.dbg", "files/busybox/libbb/ptr_to_globals.dbg"))
doc235.iconSrc = ICONPATH + "fileok.gif"
doc236 = insDoc(libbb, gLnk("S", "pw_encrypt.dbg", "files/busybox/libbb/pw_encrypt.dbg"))
doc236.iconSrc = ICONPATH + "filefail.gif"
doc237 = insDoc(libbb, gLnk("S", "read.dbg", "files/busybox/libbb/read.dbg"))
doc237.iconSrc = ICONPATH + "fileok.gif"
doc238 = insDoc(libbb, gLnk("S", "read_key.dbg", "files/busybox/libbb/read_key.dbg"))
doc238.iconSrc = ICONPATH + "fileok.gif"
doc239 = insDoc(libbb, gLnk("S", "read_printf.dbg", "files/busybox/libbb/read_printf.dbg"))
doc239.iconSrc = ICONPATH + "fileok.gif"
doc240 = insDoc(libbb, gLnk("S", "recursive_action.dbg", "files/busybox/libbb/recursive_action.dbg"))
doc240.iconSrc = ICONPATH + "fileok.gif"
doc241 = insDoc(libbb, gLnk("S", "remove_file.dbg", "files/busybox/libbb/remove_file.dbg"))
doc241.iconSrc = ICONPATH + "fileok.gif"
doc242 = insDoc(libbb, gLnk("S", "rtc.dbg", "files/busybox/libbb/rtc.dbg"))
doc242.iconSrc = ICONPATH + "fileok.gif"
doc243 = insDoc(libbb, gLnk("S", "run_shell.dbg", "files/busybox/libbb/run_shell.dbg"))
doc243.iconSrc = ICONPATH + "fileok.gif"
doc244 = insDoc(libbb, gLnk("S", "safe_gethostname.dbg", "files/busybox/libbb/safe_gethostname.dbg"))
doc244.iconSrc = ICONPATH + "filefail.gif"
doc245 = insDoc(libbb, gLnk("S", "safe_poll.dbg", "files/busybox/libbb/safe_poll.dbg"))
doc245.iconSrc = ICONPATH + "fileok.gif"
doc246 = insDoc(libbb, gLnk("S", "safe_strncpy.dbg", "files/busybox/libbb/safe_strncpy.dbg"))
doc246.iconSrc = ICONPATH + "fileok.gif"
doc247 = insDoc(libbb, gLnk("S", "safe_write.dbg", "files/busybox/libbb/safe_write.dbg"))
doc247.iconSrc = ICONPATH + "fileok.gif"
doc248 = insDoc(libbb, gLnk("S", "selinux_common.dbg", "files/busybox/libbb/selinux_common.dbg"))
doc248.iconSrc = ICONPATH + "fileok.gif"
doc249 = insDoc(libbb, gLnk("S", "setup_environment.dbg", "files/busybox/libbb/setup_environment.dbg"))
doc249.iconSrc = ICONPATH + "fileok.gif"
doc250 = insDoc(libbb, gLnk("S", "signals.dbg", "files/busybox/libbb/signals.dbg"))
doc250.iconSrc = ICONPATH + "fileok.gif"
doc251 = insDoc(libbb, gLnk("S", "simplify_path.dbg", "files/busybox/libbb/simplify_path.dbg"))
doc251.iconSrc = ICONPATH + "fileok.gif"
doc252 = insDoc(libbb, gLnk("S", "single_argv.dbg", "files/busybox/libbb/single_argv.dbg"))
doc252.iconSrc = ICONPATH + "fileok.gif"
doc253 = insDoc(libbb, gLnk("S", "skip_whitespace.dbg", "files/busybox/libbb/skip_whitespace.dbg"))
doc253.iconSrc = ICONPATH + "fileok.gif"
doc254 = insDoc(libbb, gLnk("S", "speed_table.dbg", "files/busybox/libbb/speed_table.dbg"))
doc254.iconSrc = ICONPATH + "fileok.gif"
doc255 = insDoc(libbb, gLnk("S", "str_tolower.dbg", "files/busybox/libbb/str_tolower.dbg"))
doc255.iconSrc = ICONPATH + "fileok.gif"
doc256 = insDoc(libbb, gLnk("S", "strrstr.dbg", "files/busybox/libbb/strrstr.dbg"))
doc256.iconSrc = ICONPATH + "fileok.gif"
doc257 = insDoc(libbb, gLnk("S", "time.dbg", "files/busybox/libbb/time.dbg"))
doc257.iconSrc = ICONPATH + "filefail.gif"
doc258 = insDoc(libbb, gLnk("S", "trim.dbg", "files/busybox/libbb/trim.dbg"))
doc258.iconSrc = ICONPATH + "fileok.gif"
doc259 = insDoc(libbb, gLnk("S", "u_signal_names.dbg", "files/busybox/libbb/u_signal_names.dbg"))
doc259.iconSrc = ICONPATH + "fileok.gif"
doc260 = insDoc(libbb, gLnk("S", "udp_io.dbg", "files/busybox/libbb/udp_io.dbg"))
doc260.iconSrc = ICONPATH + "filefail.gif"
doc261 = insDoc(libbb, gLnk("S", "unicode.dbg", "files/busybox/libbb/unicode.dbg"))
doc261.iconSrc = ICONPATH + "filefail.gif"
doc262 = insDoc(libbb, gLnk("S", "update_passwd.dbg", "files/busybox/libbb/update_passwd.dbg"))
doc262.iconSrc = ICONPATH + "filefail.gif"
doc263 = insDoc(libbb, gLnk("S", "utmp.dbg", "files/busybox/libbb/utmp.dbg"))
doc263.iconSrc = ICONPATH + "fileok.gif"
doc264 = insDoc(libbb, gLnk("S", "uuencode.dbg", "files/busybox/libbb/uuencode.dbg"))
doc264.iconSrc = ICONPATH + "fileok.gif"
doc265 = insDoc(libbb, gLnk("S", "vdprintf.dbg", "files/busybox/libbb/vdprintf.dbg"))
doc265.iconSrc = ICONPATH + "fileok.gif"
doc266 = insDoc(libbb, gLnk("S", "verror_msg.dbg", "files/busybox/libbb/verror_msg.dbg"))
doc266.iconSrc = ICONPATH + "filefail.gif"
doc267 = insDoc(libbb, gLnk("S", "vfork_daemon_rexec.dbg", "files/busybox/libbb/vfork_daemon_rexec.dbg"))
doc267.iconSrc = ICONPATH + "fileok.gif"
doc268 = insDoc(libbb, gLnk("S", "warn_ignoring_args.dbg", "files/busybox/libbb/warn_ignoring_args.dbg"))
doc268.iconSrc = ICONPATH + "fileok.gif"
doc269 = insDoc(libbb, gLnk("S", "wfopen.dbg", "files/busybox/libbb/wfopen.dbg"))
doc269.iconSrc = ICONPATH + "fileok.gif"
doc270 = insDoc(libbb, gLnk("S", "wfopen_input.dbg", "files/busybox/libbb/wfopen_input.dbg"))
doc270.iconSrc = ICONPATH + "fileok.gif"
doc271 = insDoc(libbb, gLnk("S", "write.dbg", "files/busybox/libbb/write.dbg"))
doc271.iconSrc = ICONPATH + "fileok.gif"
doc272 = insDoc(libbb, gLnk("S", "xatonum.dbg", "files/busybox/libbb/xatonum.dbg"))
doc272.iconSrc = ICONPATH + "fileok.gif"
doc273 = insDoc(libbb, gLnk("S", "xconnect.dbg", "files/busybox/libbb/xconnect.dbg"))
doc273.iconSrc = ICONPATH + "fileok.gif"
doc274 = insDoc(libbb, gLnk("S", "xfunc_die.dbg", "files/busybox/libbb/xfunc_die.dbg"))
doc274.iconSrc = ICONPATH + "fileok.gif"
doc275 = insDoc(libbb, gLnk("S", "xfuncs.dbg", "files/busybox/libbb/xfuncs.dbg"))
doc275.iconSrc = ICONPATH + "fileok.gif"
doc276 = insDoc(libbb, gLnk("S", "xfuncs_printf.dbg", "files/busybox/libbb/xfuncs_printf.dbg"))
doc276.iconSrc = ICONPATH + "filefail.gif"
doc277 = insDoc(libbb, gLnk("S", "xgetcwd.dbg", "files/busybox/libbb/xgetcwd.dbg"))
doc277.iconSrc = ICONPATH + "fileok.gif"
doc278 = insDoc(libbb, gLnk("S", "xgethostbyname.dbg", "files/busybox/libbb/xgethostbyname.dbg"))
doc278.iconSrc = ICONPATH + "fileok.gif"
doc279 = insDoc(libbb, gLnk("S", "xreadlink.dbg", "files/busybox/libbb/xreadlink.dbg"))
doc279.iconSrc = ICONPATH + "fileok.gif"
doc280 = insDoc(libbb, gLnk("S", "xrealloc_vector.dbg", "files/busybox/libbb/xrealloc_vector.dbg"))
doc280.iconSrc = ICONPATH + "fileok.gif"
doc281 = insDoc(libbb, gLnk("S", "xregcomp.dbg", "files/busybox/libbb/xregcomp.dbg"))
doc281.iconSrc = ICONPATH + "fileok.gif"
libpwdgrp = insFld(foldersTree, gFld("libpwdgrp", ""))
libpwdgrp.iconSrc = ICONPATH + "folderopenok.gif"
libpwdgrp.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc282 = insDoc(libpwdgrp, gLnk("S", "pwd_grp.dbg", "files/busybox/libpwdgrp/pwd_grp.dbg"))
doc282.iconSrc = ICONPATH + "fileok.gif"
doc283 = insDoc(libpwdgrp, gLnk("S", "uidgid_get.dbg", "files/busybox/libpwdgrp/uidgid_get.dbg"))
doc283.iconSrc = ICONPATH + "fileok.gif"
loginutils = insFld(foldersTree, gFld("loginutils", ""))
loginutils.iconSrc = ICONPATH + "folderopenok.gif"
loginutils.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc284 = insDoc(loginutils, gLnk("S", "add-remove-shell.dbg", "files/busybox/loginutils/add-remove-shell.dbg"))
doc284.iconSrc = ICONPATH + "fileok.gif"
doc285 = insDoc(loginutils, gLnk("S", "addgroup.dbg", "files/busybox/loginutils/addgroup.dbg"))
doc285.iconSrc = ICONPATH + "fileok.gif"
doc286 = insDoc(loginutils, gLnk("S", "adduser.dbg", "files/busybox/loginutils/adduser.dbg"))
doc286.iconSrc = ICONPATH + "fileok.gif"
doc287 = insDoc(loginutils, gLnk("S", "chpasswd.dbg", "files/busybox/loginutils/chpasswd.dbg"))
doc287.iconSrc = ICONPATH + "fileok.gif"
doc288 = insDoc(loginutils, gLnk("S", "cryptpw.dbg", "files/busybox/loginutils/cryptpw.dbg"))
doc288.iconSrc = ICONPATH + "fileok.gif"
doc289 = insDoc(loginutils, gLnk("S", "deluser.dbg", "files/busybox/loginutils/deluser.dbg"))
doc289.iconSrc = ICONPATH + "fileok.gif"
doc290 = insDoc(loginutils, gLnk("S", "getty.dbg", "files/busybox/loginutils/getty.dbg"))
doc290.iconSrc = ICONPATH + "fileok.gif"
doc291 = insDoc(loginutils, gLnk("S", "login.dbg", "files/busybox/loginutils/login.dbg"))
doc291.iconSrc = ICONPATH + "fileok.gif"
doc292 = insDoc(loginutils, gLnk("S", "passwd.dbg", "files/busybox/loginutils/passwd.dbg"))
doc292.iconSrc = ICONPATH + "fileok.gif"
doc293 = insDoc(loginutils, gLnk("S", "su.dbg", "files/busybox/loginutils/su.dbg"))
doc293.iconSrc = ICONPATH + "fileok.gif"
doc294 = insDoc(loginutils, gLnk("S", "sulogin.dbg", "files/busybox/loginutils/sulogin.dbg"))
doc294.iconSrc = ICONPATH + "fileok.gif"
doc295 = insDoc(loginutils, gLnk("S", "vlock.dbg", "files/busybox/loginutils/vlock.dbg"))
doc295.iconSrc = ICONPATH + "fileok.gif"
mailutils = insFld(foldersTree, gFld("mailutils", ""))
mailutils.iconSrc = ICONPATH + "folderopenfail.gif"
mailutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc296 = insDoc(mailutils, gLnk("S", "mail.dbg", "files/busybox/mailutils/mail.dbg"))
doc296.iconSrc = ICONPATH + "fileok.gif"
doc297 = insDoc(mailutils, gLnk("S", "mime.dbg", "files/busybox/mailutils/mime.dbg"))
doc297.iconSrc = ICONPATH + "filefail.gif"
doc298 = insDoc(mailutils, gLnk("S", "popmaildir.dbg", "files/busybox/mailutils/popmaildir.dbg"))
doc298.iconSrc = ICONPATH + "fileok.gif"
doc299 = insDoc(mailutils, gLnk("S", "sendmail.dbg", "files/busybox/mailutils/sendmail.dbg"))
doc299.iconSrc = ICONPATH + "fileok.gif"
miscutils = insFld(foldersTree, gFld("miscutils", ""))
miscutils.iconSrc = ICONPATH + "folderopenfail.gif"
miscutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc300 = insDoc(miscutils, gLnk("S", "adjtimex.dbg", "files/busybox/miscutils/adjtimex.dbg"))
doc300.iconSrc = ICONPATH + "fileok.gif"
doc301 = insDoc(miscutils, gLnk("S", "bbconfig.dbg", "files/busybox/miscutils/bbconfig.dbg"))
doc301.iconSrc = ICONPATH + "fileok.gif"
doc302 = insDoc(miscutils, gLnk("S", "beep.dbg", "files/busybox/miscutils/beep.dbg"))
doc302.iconSrc = ICONPATH + "fileok.gif"
doc303 = insDoc(miscutils, gLnk("S", "chat.dbg", "files/busybox/miscutils/chat.dbg"))
doc303.iconSrc = ICONPATH + "fileok.gif"
doc304 = insDoc(miscutils, gLnk("S", "chrt.dbg", "files/busybox/miscutils/chrt.dbg"))
doc304.iconSrc = ICONPATH + "fileok.gif"
doc305 = insDoc(miscutils, gLnk("S", "conspy.dbg", "files/busybox/miscutils/conspy.dbg"))
doc305.iconSrc = ICONPATH + "fileok.gif"
doc306 = insDoc(miscutils, gLnk("S", "crond.dbg", "files/busybox/miscutils/crond.dbg"))
doc306.iconSrc = ICONPATH + "filefail.gif"
doc307 = insDoc(miscutils, gLnk("S", "crontab.dbg", "files/busybox/miscutils/crontab.dbg"))
doc307.iconSrc = ICONPATH + "fileok.gif"
doc308 = insDoc(miscutils, gLnk("S", "dc.dbg", "files/busybox/miscutils/dc.dbg"))
doc308.iconSrc = ICONPATH + "filefail.gif"
doc309 = insDoc(miscutils, gLnk("S", "devfsd.dbg", "files/busybox/miscutils/devfsd.dbg"))
doc309.iconSrc = ICONPATH + "fileok.gif"
doc310 = insDoc(miscutils, gLnk("S", "devmem.dbg", "files/busybox/miscutils/devmem.dbg"))
doc310.iconSrc = ICONPATH + "filefail.gif"
doc311 = insDoc(miscutils, gLnk("S", "eject.dbg", "files/busybox/miscutils/eject.dbg"))
doc311.iconSrc = ICONPATH + "fileok.gif"
doc312 = insDoc(miscutils, gLnk("S", "fbsplash.dbg", "files/busybox/miscutils/fbsplash.dbg"))
doc312.iconSrc = ICONPATH + "filefail.gif"
doc313 = insDoc(miscutils, gLnk("S", "flash_eraseall.dbg", "files/busybox/miscutils/flash_eraseall.dbg"))
doc313.iconSrc = ICONPATH + "fileok.gif"
doc314 = insDoc(miscutils, gLnk("S", "flash_lock_unlock.dbg", "files/busybox/miscutils/flash_lock_unlock.dbg"))
doc314.iconSrc = ICONPATH + "fileok.gif"
doc315 = insDoc(miscutils, gLnk("S", "flashcp.dbg", "files/busybox/miscutils/flashcp.dbg"))
doc315.iconSrc = ICONPATH + "fileok.gif"
doc316 = insDoc(miscutils, gLnk("S", "hdparm.dbg", "files/busybox/miscutils/hdparm.dbg"))
doc316.iconSrc = ICONPATH + "fileok.gif"
doc317 = insDoc(miscutils, gLnk("S", "inotifyd.dbg", "files/busybox/miscutils/inotifyd.dbg"))
doc317.iconSrc = ICONPATH + "fileok.gif"
doc318 = insDoc(miscutils, gLnk("S", "ionice.dbg", "files/busybox/miscutils/ionice.dbg"))
doc318.iconSrc = ICONPATH + "fileok.gif"
doc319 = insDoc(miscutils, gLnk("S", "last.dbg", "files/busybox/miscutils/last.dbg"))
doc319.iconSrc = ICONPATH + "fileok.gif"
doc320 = insDoc(miscutils, gLnk("S", "last_fancy.dbg", "files/busybox/miscutils/last_fancy.dbg"))
doc320.iconSrc = ICONPATH + "fileok.gif"
doc321 = insDoc(miscutils, gLnk("S", "less.dbg", "files/busybox/miscutils/less.dbg"))
doc321.iconSrc = ICONPATH + "fileok.gif"
doc322 = insDoc(miscutils, gLnk("S", "makedevs.dbg", "files/busybox/miscutils/makedevs.dbg"))
doc322.iconSrc = ICONPATH + "fileok.gif"
doc323 = insDoc(miscutils, gLnk("S", "man.dbg", "files/busybox/miscutils/man.dbg"))
doc323.iconSrc = ICONPATH + "filefail.gif"
doc324 = insDoc(miscutils, gLnk("S", "microcom.dbg", "files/busybox/miscutils/microcom.dbg"))
doc324.iconSrc = ICONPATH + "fileok.gif"
doc325 = insDoc(miscutils, gLnk("S", "mountpoint.dbg", "files/busybox/miscutils/mountpoint.dbg"))
doc325.iconSrc = ICONPATH + "fileok.gif"
doc326 = insDoc(miscutils, gLnk("S", "mt.dbg", "files/busybox/miscutils/mt.dbg"))
doc326.iconSrc = ICONPATH + "fileok.gif"
doc327 = insDoc(miscutils, gLnk("S", "nandwrite.dbg", "files/busybox/miscutils/nandwrite.dbg"))
doc327.iconSrc = ICONPATH + "fileok.gif"
doc328 = insDoc(miscutils, gLnk("S", "raidautorun.dbg", "files/busybox/miscutils/raidautorun.dbg"))
doc328.iconSrc = ICONPATH + "fileok.gif"
doc329 = insDoc(miscutils, gLnk("S", "readahead.dbg", "files/busybox/miscutils/readahead.dbg"))
doc329.iconSrc = ICONPATH + "filefail.gif"
doc330 = insDoc(miscutils, gLnk("S", "rfkill.dbg", "files/busybox/miscutils/rfkill.dbg"))
doc330.iconSrc = ICONPATH + "fileok.gif"
doc331 = insDoc(miscutils, gLnk("S", "runlevel.dbg", "files/busybox/miscutils/runlevel.dbg"))
doc331.iconSrc = ICONPATH + "fileok.gif"
doc332 = insDoc(miscutils, gLnk("S", "rx.dbg", "files/busybox/miscutils/rx.dbg"))
doc332.iconSrc = ICONPATH + "fileok.gif"
doc333 = insDoc(miscutils, gLnk("S", "setsid.dbg", "files/busybox/miscutils/setsid.dbg"))
doc333.iconSrc = ICONPATH + "fileok.gif"
doc334 = insDoc(miscutils, gLnk("S", "strings.dbg", "files/busybox/miscutils/strings.dbg"))
doc334.iconSrc = ICONPATH + "fileok.gif"
doc335 = insDoc(miscutils, gLnk("S", "taskset.dbg", "files/busybox/miscutils/taskset.dbg"))
doc335.iconSrc = ICONPATH + "filefail.gif"
doc336 = insDoc(miscutils, gLnk("S", "time.dbg", "files/busybox/miscutils/time.dbg"))
doc336.iconSrc = ICONPATH + "fileok.gif"
doc337 = insDoc(miscutils, gLnk("S", "timeout.dbg", "files/busybox/miscutils/timeout.dbg"))
doc337.iconSrc = ICONPATH + "fileok.gif"
doc338 = insDoc(miscutils, gLnk("S", "ttysize.dbg", "files/busybox/miscutils/ttysize.dbg"))
doc338.iconSrc = ICONPATH + "fileok.gif"
doc339 = insDoc(miscutils, gLnk("S", "ubi_attach_detach.dbg", "files/busybox/miscutils/ubi_attach_detach.dbg"))
doc339.iconSrc = ICONPATH + "fileok.gif"
doc340 = insDoc(miscutils, gLnk("S", "volname.dbg", "files/busybox/miscutils/volname.dbg"))
doc340.iconSrc = ICONPATH + "fileok.gif"
doc341 = insDoc(miscutils, gLnk("S", "wall.dbg", "files/busybox/miscutils/wall.dbg"))
doc341.iconSrc = ICONPATH + "fileok.gif"
doc342 = insDoc(miscutils, gLnk("S", "watchdog.dbg", "files/busybox/miscutils/watchdog.dbg"))
doc342.iconSrc = ICONPATH + "fileok.gif"
modutils = insFld(foldersTree, gFld("modutils", ""))
modutils.iconSrc = ICONPATH + "folderopenfail.gif"
modutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc343 = insDoc(modutils, gLnk("S", "depmod.dbg", "files/busybox/modutils/depmod.dbg"))
doc343.iconSrc = ICONPATH + "filefail.gif"
doc344 = insDoc(modutils, gLnk("S", "insmod.dbg", "files/busybox/modutils/insmod.dbg"))
doc344.iconSrc = ICONPATH + "fileok.gif"
doc345 = insDoc(modutils, gLnk("S", "lsmod.dbg", "files/busybox/modutils/lsmod.dbg"))
doc345.iconSrc = ICONPATH + "fileok.gif"
doc346 = insDoc(modutils, gLnk("S", "modinfo.dbg", "files/busybox/modutils/modinfo.dbg"))
doc346.iconSrc = ICONPATH + "fileok.gif"
doc347 = insDoc(modutils, gLnk("S", "modprobe-small.dbg", "files/busybox/modutils/modprobe-small.dbg"))
doc347.iconSrc = ICONPATH + "filefail.gif"
doc348 = insDoc(modutils, gLnk("S", "modprobe.dbg", "files/busybox/modutils/modprobe.dbg"))
doc348.iconSrc = ICONPATH + "fileok.gif"
doc349 = insDoc(modutils, gLnk("S", "modutils-24.dbg", "files/busybox/modutils/modutils-24.dbg"))
doc349.iconSrc = ICONPATH + "filefail.gif"
doc350 = insDoc(modutils, gLnk("S", "modutils.dbg", "files/busybox/modutils/modutils.dbg"))
doc350.iconSrc = ICONPATH + "fileok.gif"
doc351 = insDoc(modutils, gLnk("S", "rmmod.dbg", "files/busybox/modutils/rmmod.dbg"))
doc351.iconSrc = ICONPATH + "fileok.gif"
networking = insFld(foldersTree, gFld("networking", ""))
networking.iconSrc = ICONPATH + "folderopenfail.gif"
networking.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc352 = insDoc(networking, gLnk("S", "arp.dbg", "files/busybox/networking/arp.dbg"))
doc352.iconSrc = ICONPATH + "fileok.gif"
doc353 = insDoc(networking, gLnk("S", "arping.dbg", "files/busybox/networking/arping.dbg"))
doc353.iconSrc = ICONPATH + "filefail.gif"
doc354 = insDoc(networking, gLnk("S", "brctl.dbg", "files/busybox/networking/brctl.dbg"))
doc354.iconSrc = ICONPATH + "fileok.gif"
doc355 = insDoc(networking, gLnk("S", "dnsd.dbg", "files/busybox/networking/dnsd.dbg"))
doc355.iconSrc = ICONPATH + "fileok.gif"
doc356 = insDoc(networking, gLnk("S", "ether-wake.dbg", "files/busybox/networking/ether-wake.dbg"))
doc356.iconSrc = ICONPATH + "fileok.gif"
doc357 = insDoc(networking, gLnk("S", "ftpd.dbg", "files/busybox/networking/ftpd.dbg"))
doc357.iconSrc = ICONPATH + "filefail.gif"
doc358 = insDoc(networking, gLnk("S", "ftpgetput.dbg", "files/busybox/networking/ftpgetput.dbg"))
doc358.iconSrc = ICONPATH + "fileok.gif"
doc359 = insDoc(networking, gLnk("S", "hostname.dbg", "files/busybox/networking/hostname.dbg"))
doc359.iconSrc = ICONPATH + "filefail.gif"
doc360 = insDoc(networking, gLnk("S", "httpd.dbg", "files/busybox/networking/httpd.dbg"))
doc360.iconSrc = ICONPATH + "filefail.gif"
doc361 = insDoc(networking, gLnk("S", "ifconfig.dbg", "files/busybox/networking/ifconfig.dbg"))
doc361.iconSrc = ICONPATH + "fileok.gif"
doc362 = insDoc(networking, gLnk("S", "ifenslave.dbg", "files/busybox/networking/ifenslave.dbg"))
doc362.iconSrc = ICONPATH + "fileok.gif"
doc363 = insDoc(networking, gLnk("S", "ifplugd.dbg", "files/busybox/networking/ifplugd.dbg"))
doc363.iconSrc = ICONPATH + "fileok.gif"
doc364 = insDoc(networking, gLnk("S", "ifupdown.dbg", "files/busybox/networking/ifupdown.dbg"))
doc364.iconSrc = ICONPATH + "fileok.gif"
doc365 = insDoc(networking, gLnk("S", "inetd.dbg", "files/busybox/networking/inetd.dbg"))
doc365.iconSrc = ICONPATH + "fileok.gif"
doc366 = insDoc(networking, gLnk("S", "interface.dbg", "files/busybox/networking/interface.dbg"))
doc366.iconSrc = ICONPATH + "fileok.gif"
doc367 = insDoc(networking, gLnk("S", "ip.dbg", "files/busybox/networking/ip.dbg"))
doc367.iconSrc = ICONPATH + "fileok.gif"
doc368 = insDoc(networking, gLnk("S", "ipcalc.dbg", "files/busybox/networking/ipcalc.dbg"))
doc368.iconSrc = ICONPATH + "fileok.gif"
doc369 = insDoc(networking, gLnk("S", "isrv.dbg", "files/busybox/networking/isrv.dbg"))
doc369.iconSrc = ICONPATH + "fileok.gif"
doc370 = insDoc(networking, gLnk("S", "isrv_identd.dbg", "files/busybox/networking/isrv_identd.dbg"))
doc370.iconSrc = ICONPATH + "fileok.gif"
libiproute = insFld(networking, gFld("libiproute", ""))
libiproute.iconSrc = ICONPATH + "folderopenok.gif"
libiproute.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc371 = insDoc(libiproute, gLnk("S", "ip_parse_common_args.dbg", "files/busybox/networking/libiproute/ip_parse_common_args.dbg"))
doc371.iconSrc = ICONPATH + "fileok.gif"
doc372 = insDoc(libiproute, gLnk("S", "ipaddress.dbg", "files/busybox/networking/libiproute/ipaddress.dbg"))
doc372.iconSrc = ICONPATH + "fileok.gif"
doc373 = insDoc(libiproute, gLnk("S", "iplink.dbg", "files/busybox/networking/libiproute/iplink.dbg"))
doc373.iconSrc = ICONPATH + "fileok.gif"
doc374 = insDoc(libiproute, gLnk("S", "iproute.dbg", "files/busybox/networking/libiproute/iproute.dbg"))
doc374.iconSrc = ICONPATH + "fileok.gif"
doc375 = insDoc(libiproute, gLnk("S", "iprule.dbg", "files/busybox/networking/libiproute/iprule.dbg"))
doc375.iconSrc = ICONPATH + "fileok.gif"
doc376 = insDoc(libiproute, gLnk("S", "iptunnel.dbg", "files/busybox/networking/libiproute/iptunnel.dbg"))
doc376.iconSrc = ICONPATH + "fileok.gif"
doc377 = insDoc(libiproute, gLnk("S", "libnetlink.dbg", "files/busybox/networking/libiproute/libnetlink.dbg"))
doc377.iconSrc = ICONPATH + "fileok.gif"
doc378 = insDoc(libiproute, gLnk("S", "ll_addr.dbg", "files/busybox/networking/libiproute/ll_addr.dbg"))
doc378.iconSrc = ICONPATH + "fileok.gif"
doc379 = insDoc(libiproute, gLnk("S", "ll_map.dbg", "files/busybox/networking/libiproute/ll_map.dbg"))
doc379.iconSrc = ICONPATH + "fileok.gif"
doc380 = insDoc(libiproute, gLnk("S", "ll_proto.dbg", "files/busybox/networking/libiproute/ll_proto.dbg"))
doc380.iconSrc = ICONPATH + "fileok.gif"
doc381 = insDoc(libiproute, gLnk("S", "ll_types.dbg", "files/busybox/networking/libiproute/ll_types.dbg"))
doc381.iconSrc = ICONPATH + "fileok.gif"
doc382 = insDoc(libiproute, gLnk("S", "rt_names.dbg", "files/busybox/networking/libiproute/rt_names.dbg"))
doc382.iconSrc = ICONPATH + "fileok.gif"
doc383 = insDoc(libiproute, gLnk("S", "rtm_map.dbg", "files/busybox/networking/libiproute/rtm_map.dbg"))
doc383.iconSrc = ICONPATH + "fileok.gif"
doc384 = insDoc(libiproute, gLnk("S", "utils.dbg", "files/busybox/networking/libiproute/utils.dbg"))
doc384.iconSrc = ICONPATH + "fileok.gif"
doc385 = insDoc(networking, gLnk("S", "nameif.dbg", "files/busybox/networking/nameif.dbg"))
doc385.iconSrc = ICONPATH + "fileok.gif"
doc386 = insDoc(networking, gLnk("S", "nbd-client.dbg", "files/busybox/networking/nbd-client.dbg"))
doc386.iconSrc = ICONPATH + "fileok.gif"
doc387 = insDoc(networking, gLnk("S", "nc.dbg", "files/busybox/networking/nc.dbg"))
doc387.iconSrc = ICONPATH + "fileok.gif"
doc388 = insDoc(networking, gLnk("S", "netstat.dbg", "files/busybox/networking/netstat.dbg"))
doc388.iconSrc = ICONPATH + "filefail.gif"
doc389 = insDoc(networking, gLnk("S", "nslookup.dbg", "files/busybox/networking/nslookup.dbg"))
doc389.iconSrc = ICONPATH + "fileok.gif"
doc390 = insDoc(networking, gLnk("S", "ntpd.dbg", "files/busybox/networking/ntpd.dbg"))
doc390.iconSrc = ICONPATH + "fileok.gif"
doc391 = insDoc(networking, gLnk("S", "ping.dbg", "files/busybox/networking/ping.dbg"))
doc391.iconSrc = ICONPATH + "fileok.gif"
doc392 = insDoc(networking, gLnk("S", "pscan.dbg", "files/busybox/networking/pscan.dbg"))
doc392.iconSrc = ICONPATH + "fileok.gif"
doc393 = insDoc(networking, gLnk("S", "route.dbg", "files/busybox/networking/route.dbg"))
doc393.iconSrc = ICONPATH + "fileok.gif"
doc394 = insDoc(networking, gLnk("S", "slattach.dbg", "files/busybox/networking/slattach.dbg"))
doc394.iconSrc = ICONPATH + "fileok.gif"
doc395 = insDoc(networking, gLnk("S", "tcpudp.dbg", "files/busybox/networking/tcpudp.dbg"))
doc395.iconSrc = ICONPATH + "fileok.gif"
doc396 = insDoc(networking, gLnk("S", "tcpudp_perhost.dbg", "files/busybox/networking/tcpudp_perhost.dbg"))
doc396.iconSrc = ICONPATH + "fileok.gif"
doc397 = insDoc(networking, gLnk("S", "telnet.dbg", "files/busybox/networking/telnet.dbg"))
doc397.iconSrc = ICONPATH + "fileok.gif"
doc398 = insDoc(networking, gLnk("S", "telnetd.dbg", "files/busybox/networking/telnetd.dbg"))
doc398.iconSrc = ICONPATH + "fileok.gif"
doc399 = insDoc(networking, gLnk("S", "tftp.dbg", "files/busybox/networking/tftp.dbg"))
doc399.iconSrc = ICONPATH + "fileok.gif"
doc400 = insDoc(networking, gLnk("S", "traceroute.dbg", "files/busybox/networking/traceroute.dbg"))
doc400.iconSrc = ICONPATH + "fileok.gif"
doc401 = insDoc(networking, gLnk("S", "tunctl.dbg", "files/busybox/networking/tunctl.dbg"))
doc401.iconSrc = ICONPATH + "fileok.gif"
udhcp = insFld(networking, gFld("udhcp", ""))
udhcp.iconSrc = ICONPATH + "folderopenok.gif"
udhcp.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc402 = insDoc(udhcp, gLnk("S", "arpping.dbg", "files/busybox/networking/udhcp/arpping.dbg"))
doc402.iconSrc = ICONPATH + "fileok.gif"
doc403 = insDoc(udhcp, gLnk("S", "common.dbg", "files/busybox/networking/udhcp/common.dbg"))
doc403.iconSrc = ICONPATH + "fileok.gif"
doc404 = insDoc(udhcp, gLnk("S", "dhcpc.dbg", "files/busybox/networking/udhcp/dhcpc.dbg"))
doc404.iconSrc = ICONPATH + "fileok.gif"
doc405 = insDoc(udhcp, gLnk("S", "dhcpd.dbg", "files/busybox/networking/udhcp/dhcpd.dbg"))
doc405.iconSrc = ICONPATH + "fileok.gif"
doc406 = insDoc(udhcp, gLnk("S", "dhcprelay.dbg", "files/busybox/networking/udhcp/dhcprelay.dbg"))
doc406.iconSrc = ICONPATH + "fileok.gif"
doc407 = insDoc(udhcp, gLnk("S", "domain_codec.dbg", "files/busybox/networking/udhcp/domain_codec.dbg"))
doc407.iconSrc = ICONPATH + "fileok.gif"
doc408 = insDoc(udhcp, gLnk("S", "dumpleases.dbg", "files/busybox/networking/udhcp/dumpleases.dbg"))
doc408.iconSrc = ICONPATH + "fileok.gif"
doc409 = insDoc(udhcp, gLnk("S", "files.dbg", "files/busybox/networking/udhcp/files.dbg"))
doc409.iconSrc = ICONPATH + "fileok.gif"
doc410 = insDoc(udhcp, gLnk("S", "leases.dbg", "files/busybox/networking/udhcp/leases.dbg"))
doc410.iconSrc = ICONPATH + "fileok.gif"
doc411 = insDoc(udhcp, gLnk("S", "packet.dbg", "files/busybox/networking/udhcp/packet.dbg"))
doc411.iconSrc = ICONPATH + "fileok.gif"
doc412 = insDoc(udhcp, gLnk("S", "signalpipe.dbg", "files/busybox/networking/udhcp/signalpipe.dbg"))
doc412.iconSrc = ICONPATH + "fileok.gif"
doc413 = insDoc(udhcp, gLnk("S", "socket.dbg", "files/busybox/networking/udhcp/socket.dbg"))
doc413.iconSrc = ICONPATH + "fileok.gif"
doc414 = insDoc(udhcp, gLnk("S", "static_leases.dbg", "files/busybox/networking/udhcp/static_leases.dbg"))
doc414.iconSrc = ICONPATH + "fileok.gif"
doc415 = insDoc(networking, gLnk("S", "vconfig.dbg", "files/busybox/networking/vconfig.dbg"))
doc415.iconSrc = ICONPATH + "fileok.gif"
doc416 = insDoc(networking, gLnk("S", "wget.dbg", "files/busybox/networking/wget.dbg"))
doc416.iconSrc = ICONPATH + "filefail.gif"
doc417 = insDoc(networking, gLnk("S", "zcip.dbg", "files/busybox/networking/zcip.dbg"))
doc417.iconSrc = ICONPATH + "fileok.gif"
printutils = insFld(foldersTree, gFld("printutils", ""))
printutils.iconSrc = ICONPATH + "folderopenfail.gif"
printutils.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc418 = insDoc(printutils, gLnk("S", "lpd.dbg", "files/busybox/printutils/lpd.dbg"))
doc418.iconSrc = ICONPATH + "filefail.gif"
doc419 = insDoc(printutils, gLnk("S", "lpr.dbg", "files/busybox/printutils/lpr.dbg"))
doc419.iconSrc = ICONPATH + "fileok.gif"
procps = insFld(foldersTree, gFld("procps", ""))
procps.iconSrc = ICONPATH + "folderopenfail.gif"
procps.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc420 = insDoc(procps, gLnk("S", "free.dbg", "files/busybox/procps/free.dbg"))
doc420.iconSrc = ICONPATH + "fileok.gif"
doc421 = insDoc(procps, gLnk("S", "fuser.dbg", "files/busybox/procps/fuser.dbg"))
doc421.iconSrc = ICONPATH + "fileok.gif"
doc422 = insDoc(procps, gLnk("S", "iostat.dbg", "files/busybox/procps/iostat.dbg"))
doc422.iconSrc = ICONPATH + "fileok.gif"
doc423 = insDoc(procps, gLnk("S", "kill.dbg", "files/busybox/procps/kill.dbg"))
doc423.iconSrc = ICONPATH + "fileok.gif"
doc424 = insDoc(procps, gLnk("S", "mpstat.dbg", "files/busybox/procps/mpstat.dbg"))
doc424.iconSrc = ICONPATH + "fileok.gif"
doc425 = insDoc(procps, gLnk("S", "nmeter.dbg", "files/busybox/procps/nmeter.dbg"))
doc425.iconSrc = ICONPATH + "fileok.gif"
doc426 = insDoc(procps, gLnk("S", "pgrep.dbg", "files/busybox/procps/pgrep.dbg"))
doc426.iconSrc = ICONPATH + "fileok.gif"
doc427 = insDoc(procps, gLnk("S", "pidof.dbg", "files/busybox/procps/pidof.dbg"))
doc427.iconSrc = ICONPATH + "fileok.gif"
doc428 = insDoc(procps, gLnk("S", "pmap.dbg", "files/busybox/procps/pmap.dbg"))
doc428.iconSrc = ICONPATH + "fileok.gif"
doc429 = insDoc(procps, gLnk("S", "powertop.dbg", "files/busybox/procps/powertop.dbg"))
doc429.iconSrc = ICONPATH + "filefail.gif"
doc430 = insDoc(procps, gLnk("S", "ps.dbg", "files/busybox/procps/ps.dbg"))
doc430.iconSrc = ICONPATH + "fileok.gif"
doc431 = insDoc(procps, gLnk("S", "renice.dbg", "files/busybox/procps/renice.dbg"))
doc431.iconSrc = ICONPATH + "fileok.gif"
doc432 = insDoc(procps, gLnk("S", "smemcap.dbg", "files/busybox/procps/smemcap.dbg"))
doc432.iconSrc = ICONPATH + "fileok.gif"
doc433 = insDoc(procps, gLnk("S", "sysctl.dbg", "files/busybox/procps/sysctl.dbg"))
doc433.iconSrc = ICONPATH + "fileok.gif"
doc434 = insDoc(procps, gLnk("S", "top.dbg", "files/busybox/procps/top.dbg"))
doc434.iconSrc = ICONPATH + "filefail.gif"
doc435 = insDoc(procps, gLnk("S", "uptime.dbg", "files/busybox/procps/uptime.dbg"))
doc435.iconSrc = ICONPATH + "fileok.gif"
doc436 = insDoc(procps, gLnk("S", "watch.dbg", "files/busybox/procps/watch.dbg"))
doc436.iconSrc = ICONPATH + "fileok.gif"
runit = insFld(foldersTree, gFld("runit", ""))
runit.iconSrc = ICONPATH + "folderopenfail.gif"
runit.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc437 = insDoc(runit, gLnk("S", "chpst.dbg", "files/busybox/runit/chpst.dbg"))
doc437.iconSrc = ICONPATH + "fileok.gif"
doc438 = insDoc(runit, gLnk("S", "runsv.dbg", "files/busybox/runit/runsv.dbg"))
doc438.iconSrc = ICONPATH + "fileok.gif"
doc439 = insDoc(runit, gLnk("S", "runsvdir.dbg", "files/busybox/runit/runsvdir.dbg"))
doc439.iconSrc = ICONPATH + "fileok.gif"
doc440 = insDoc(runit, gLnk("S", "sv.dbg", "files/busybox/runit/sv.dbg"))
doc440.iconSrc = ICONPATH + "fileok.gif"
doc441 = insDoc(runit, gLnk("S", "svlogd.dbg", "files/busybox/runit/svlogd.dbg"))
doc441.iconSrc = ICONPATH + "filefail.gif"
selinux = insFld(foldersTree, gFld("selinux", ""))
selinux.iconSrc = ICONPATH + "folderopenok.gif"
selinux.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc442 = insDoc(selinux, gLnk("S", "chcon.dbg", "files/busybox/selinux/chcon.dbg"))
doc442.iconSrc = ICONPATH + "fileok.gif"
doc443 = insDoc(selinux, gLnk("S", "getenforce.dbg", "files/busybox/selinux/getenforce.dbg"))
doc443.iconSrc = ICONPATH + "fileok.gif"
doc444 = insDoc(selinux, gLnk("S", "getsebool.dbg", "files/busybox/selinux/getsebool.dbg"))
doc444.iconSrc = ICONPATH + "fileok.gif"
doc445 = insDoc(selinux, gLnk("S", "load_policy.dbg", "files/busybox/selinux/load_policy.dbg"))
doc445.iconSrc = ICONPATH + "fileok.gif"
doc446 = insDoc(selinux, gLnk("S", "matchpathcon.dbg", "files/busybox/selinux/matchpathcon.dbg"))
doc446.iconSrc = ICONPATH + "fileok.gif"
doc447 = insDoc(selinux, gLnk("S", "runcon.dbg", "files/busybox/selinux/runcon.dbg"))
doc447.iconSrc = ICONPATH + "fileok.gif"
doc448 = insDoc(selinux, gLnk("S", "selinuxenabled.dbg", "files/busybox/selinux/selinuxenabled.dbg"))
doc448.iconSrc = ICONPATH + "fileok.gif"
doc449 = insDoc(selinux, gLnk("S", "sestatus.dbg", "files/busybox/selinux/sestatus.dbg"))
doc449.iconSrc = ICONPATH + "fileok.gif"
doc450 = insDoc(selinux, gLnk("S", "setenforce.dbg", "files/busybox/selinux/setenforce.dbg"))
doc450.iconSrc = ICONPATH + "fileok.gif"
doc451 = insDoc(selinux, gLnk("S", "setfiles.dbg", "files/busybox/selinux/setfiles.dbg"))
doc451.iconSrc = ICONPATH + "fileok.gif"
doc452 = insDoc(selinux, gLnk("S", "setsebool.dbg", "files/busybox/selinux/setsebool.dbg"))
doc452.iconSrc = ICONPATH + "fileok.gif"
shell = insFld(foldersTree, gFld("shell", ""))
shell.iconSrc = ICONPATH + "folderopenfail.gif"
shell.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc453 = insDoc(shell, gLnk("S", "ash.dbg", "files/busybox/shell/ash.dbg"))
doc453.iconSrc = ICONPATH + "filefail.gif"
doc454 = insDoc(shell, gLnk("S", "ash_ptr_hack.dbg", "files/busybox/shell/ash_ptr_hack.dbg"))
doc454.iconSrc = ICONPATH + "fileok.gif"
doc455 = insDoc(shell, gLnk("S", "cttyhack.dbg", "files/busybox/shell/cttyhack.dbg"))
doc455.iconSrc = ICONPATH + "fileok.gif"
doc456 = insDoc(shell, gLnk("S", "hush.dbg", "files/busybox/shell/hush.dbg"))
doc456.iconSrc = ICONPATH + "filefail.gif"
doc457 = insDoc(shell, gLnk("S", "match.dbg", "files/busybox/shell/match.dbg"))
doc457.iconSrc = ICONPATH + "fileok.gif"
doc458 = insDoc(shell, gLnk("S", "math.dbg", "files/busybox/shell/math.dbg"))
doc458.iconSrc = ICONPATH + "fileok.gif"
doc459 = insDoc(shell, gLnk("S", "random.dbg", "files/busybox/shell/random.dbg"))
doc459.iconSrc = ICONPATH + "fileok.gif"
doc460 = insDoc(shell, gLnk("S", "shell_common.dbg", "files/busybox/shell/shell_common.dbg"))
doc460.iconSrc = ICONPATH + "fileok.gif"
sysklogd = insFld(foldersTree, gFld("sysklogd", ""))
sysklogd.iconSrc = ICONPATH + "folderopenfail.gif"
sysklogd.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc461 = insDoc(sysklogd, gLnk("S", "klogd.dbg", "files/busybox/sysklogd/klogd.dbg"))
doc461.iconSrc = ICONPATH + "filefail.gif"
doc462 = insDoc(sysklogd, gLnk("S", "logread.dbg", "files/busybox/sysklogd/logread.dbg"))
doc462.iconSrc = ICONPATH + "fileok.gif"
doc463 = insDoc(sysklogd, gLnk("S", "syslogd_and_logger.dbg", "files/busybox/sysklogd/syslogd_and_logger.dbg"))
doc463.iconSrc = ICONPATH + "filefail.gif"
util_linux = insFld(foldersTree, gFld("util-linux", ""))
util_linux.iconSrc = ICONPATH + "folderopenfail.gif"
util_linux.iconSrcClosed = ICONPATH + "folderclosedfail.gif"
doc464 = insDoc(util_linux, gLnk("S", "acpid.dbg", "files/busybox/util-linux/acpid.dbg"))
doc464.iconSrc = ICONPATH + "fileok.gif"
doc465 = insDoc(util_linux, gLnk("S", "blkid.dbg", "files/busybox/util-linux/blkid.dbg"))
doc465.iconSrc = ICONPATH + "fileok.gif"
doc466 = insDoc(util_linux, gLnk("S", "blockdev.dbg", "files/busybox/util-linux/blockdev.dbg"))
doc466.iconSrc = ICONPATH + "fileok.gif"
doc467 = insDoc(util_linux, gLnk("S", "dmesg.dbg", "files/busybox/util-linux/dmesg.dbg"))
doc467.iconSrc = ICONPATH + "fileok.gif"
doc468 = insDoc(util_linux, gLnk("S", "fbset.dbg", "files/busybox/util-linux/fbset.dbg"))
doc468.iconSrc = ICONPATH + "fileok.gif"
doc469 = insDoc(util_linux, gLnk("S", "fdformat.dbg", "files/busybox/util-linux/fdformat.dbg"))
doc469.iconSrc = ICONPATH + "fileok.gif"
doc470 = insDoc(util_linux, gLnk("S", "fdisk.dbg", "files/busybox/util-linux/fdisk.dbg"))
doc470.iconSrc = ICONPATH + "fileok.gif"
doc471 = insDoc(util_linux, gLnk("S", "findfs.dbg", "files/busybox/util-linux/findfs.dbg"))
doc471.iconSrc = ICONPATH + "fileok.gif"
doc472 = insDoc(util_linux, gLnk("S", "flock.dbg", "files/busybox/util-linux/flock.dbg"))
doc472.iconSrc = ICONPATH + "fileok.gif"
doc473 = insDoc(util_linux, gLnk("S", "freeramdisk.dbg", "files/busybox/util-linux/freeramdisk.dbg"))
doc473.iconSrc = ICONPATH + "fileok.gif"
doc474 = insDoc(util_linux, gLnk("S", "fsck_minix.dbg", "files/busybox/util-linux/fsck_minix.dbg"))
doc474.iconSrc = ICONPATH + "fileok.gif"
doc475 = insDoc(util_linux, gLnk("S", "getopt.dbg", "files/busybox/util-linux/getopt.dbg"))
doc475.iconSrc = ICONPATH + "fileok.gif"
doc476 = insDoc(util_linux, gLnk("S", "hexdump.dbg", "files/busybox/util-linux/hexdump.dbg"))
doc476.iconSrc = ICONPATH + "fileok.gif"
doc477 = insDoc(util_linux, gLnk("S", "hwclock.dbg", "files/busybox/util-linux/hwclock.dbg"))
doc477.iconSrc = ICONPATH + "filefail.gif"
doc478 = insDoc(util_linux, gLnk("S", "ipcrm.dbg", "files/busybox/util-linux/ipcrm.dbg"))
doc478.iconSrc = ICONPATH + "fileok.gif"
doc479 = insDoc(util_linux, gLnk("S", "ipcs.dbg", "files/busybox/util-linux/ipcs.dbg"))
doc479.iconSrc = ICONPATH + "fileok.gif"
doc480 = insDoc(util_linux, gLnk("S", "losetup.dbg", "files/busybox/util-linux/losetup.dbg"))
doc480.iconSrc = ICONPATH + "fileok.gif"
doc481 = insDoc(util_linux, gLnk("S", "lspci.dbg", "files/busybox/util-linux/lspci.dbg"))
doc481.iconSrc = ICONPATH + "fileok.gif"
doc482 = insDoc(util_linux, gLnk("S", "lsusb.dbg", "files/busybox/util-linux/lsusb.dbg"))
doc482.iconSrc = ICONPATH + "fileok.gif"
doc483 = insDoc(util_linux, gLnk("S", "mdev.dbg", "files/busybox/util-linux/mdev.dbg"))
doc483.iconSrc = ICONPATH + "filefail.gif"
doc484 = insDoc(util_linux, gLnk("S", "mkfs_ext2.dbg", "files/busybox/util-linux/mkfs_ext2.dbg"))
doc484.iconSrc = ICONPATH + "fileok.gif"
doc485 = insDoc(util_linux, gLnk("S", "mkfs_minix.dbg", "files/busybox/util-linux/mkfs_minix.dbg"))
doc485.iconSrc = ICONPATH + "fileok.gif"
doc486 = insDoc(util_linux, gLnk("S", "mkfs_reiser.dbg", "files/busybox/util-linux/mkfs_reiser.dbg"))
doc486.iconSrc = ICONPATH + "fileok.gif"
doc487 = insDoc(util_linux, gLnk("S", "mkfs_vfat.dbg", "files/busybox/util-linux/mkfs_vfat.dbg"))
doc487.iconSrc = ICONPATH + "fileok.gif"
doc488 = insDoc(util_linux, gLnk("S", "mkswap.dbg", "files/busybox/util-linux/mkswap.dbg"))
doc488.iconSrc = ICONPATH + "fileok.gif"
doc489 = insDoc(util_linux, gLnk("S", "more.dbg", "files/busybox/util-linux/more.dbg"))
doc489.iconSrc = ICONPATH + "fileok.gif"
doc490 = insDoc(util_linux, gLnk("S", "mount.dbg", "files/busybox/util-linux/mount.dbg"))
doc490.iconSrc = ICONPATH + "filefail.gif"
doc491 = insDoc(util_linux, gLnk("S", "pivot_root.dbg", "files/busybox/util-linux/pivot_root.dbg"))
doc491.iconSrc = ICONPATH + "fileok.gif"
doc492 = insDoc(util_linux, gLnk("S", "rdate.dbg", "files/busybox/util-linux/rdate.dbg"))
doc492.iconSrc = ICONPATH + "fileok.gif"
doc493 = insDoc(util_linux, gLnk("S", "rdev.dbg", "files/busybox/util-linux/rdev.dbg"))
doc493.iconSrc = ICONPATH + "fileok.gif"
doc494 = insDoc(util_linux, gLnk("S", "readprofile.dbg", "files/busybox/util-linux/readprofile.dbg"))
doc494.iconSrc = ICONPATH + "fileok.gif"
doc495 = insDoc(util_linux, gLnk("S", "rev.dbg", "files/busybox/util-linux/rev.dbg"))
doc495.iconSrc = ICONPATH + "fileok.gif"
doc496 = insDoc(util_linux, gLnk("S", "rtcwake.dbg", "files/busybox/util-linux/rtcwake.dbg"))
doc496.iconSrc = ICONPATH + "fileok.gif"
doc497 = insDoc(util_linux, gLnk("S", "script.dbg", "files/busybox/util-linux/script.dbg"))
doc497.iconSrc = ICONPATH + "fileok.gif"
doc498 = insDoc(util_linux, gLnk("S", "scriptreplay.dbg", "files/busybox/util-linux/scriptreplay.dbg"))
doc498.iconSrc = ICONPATH + "fileok.gif"
doc499 = insDoc(util_linux, gLnk("S", "setarch.dbg", "files/busybox/util-linux/setarch.dbg"))
doc499.iconSrc = ICONPATH + "fileok.gif"
doc500 = insDoc(util_linux, gLnk("S", "swaponoff.dbg", "files/busybox/util-linux/swaponoff.dbg"))
doc500.iconSrc = ICONPATH + "fileok.gif"
doc501 = insDoc(util_linux, gLnk("S", "switch_root.dbg", "files/busybox/util-linux/switch_root.dbg"))
doc501.iconSrc = ICONPATH + "fileok.gif"
doc502 = insDoc(util_linux, gLnk("S", "umount.dbg", "files/busybox/util-linux/umount.dbg"))
doc502.iconSrc = ICONPATH + "fileok.gif"
volume_id = insFld(util_linux, gFld("volume_id", ""))
volume_id.iconSrc = ICONPATH + "folderopenok.gif"
volume_id.iconSrcClosed = ICONPATH + "folderclosedok.gif"
doc503 = insDoc(volume_id, gLnk("S", "btrfs.dbg", "files/busybox/util-linux/volume_id/btrfs.dbg"))
doc503.iconSrc = ICONPATH + "fileok.gif"
doc504 = insDoc(volume_id, gLnk("S", "cramfs.dbg", "files/busybox/util-linux/volume_id/cramfs.dbg"))
doc504.iconSrc = ICONPATH + "fileok.gif"
doc505 = insDoc(volume_id, gLnk("S", "ext.dbg", "files/busybox/util-linux/volume_id/ext.dbg"))
doc505.iconSrc = ICONPATH + "fileok.gif"
doc506 = insDoc(volume_id, gLnk("S", "fat.dbg", "files/busybox/util-linux/volume_id/fat.dbg"))
doc506.iconSrc = ICONPATH + "fileok.gif"
doc507 = insDoc(volume_id, gLnk("S", "get_devname.dbg", "files/busybox/util-linux/volume_id/get_devname.dbg"))
doc507.iconSrc = ICONPATH + "fileok.gif"
doc508 = insDoc(volume_id, gLnk("S", "hfs.dbg", "files/busybox/util-linux/volume_id/hfs.dbg"))
doc508.iconSrc = ICONPATH + "fileok.gif"
doc509 = insDoc(volume_id, gLnk("S", "iso9660.dbg", "files/busybox/util-linux/volume_id/iso9660.dbg"))
doc509.iconSrc = ICONPATH + "fileok.gif"
doc510 = insDoc(volume_id, gLnk("S", "jfs.dbg", "files/busybox/util-linux/volume_id/jfs.dbg"))
doc510.iconSrc = ICONPATH + "fileok.gif"
doc511 = insDoc(volume_id, gLnk("S", "linux_raid.dbg", "files/busybox/util-linux/volume_id/linux_raid.dbg"))
doc511.iconSrc = ICONPATH + "fileok.gif"
doc512 = insDoc(volume_id, gLnk("S", "linux_swap.dbg", "files/busybox/util-linux/volume_id/linux_swap.dbg"))
doc512.iconSrc = ICONPATH + "fileok.gif"
doc513 = insDoc(volume_id, gLnk("S", "luks.dbg", "files/busybox/util-linux/volume_id/luks.dbg"))
doc513.iconSrc = ICONPATH + "fileok.gif"
doc514 = insDoc(volume_id, gLnk("S", "ntfs.dbg", "files/busybox/util-linux/volume_id/ntfs.dbg"))
doc514.iconSrc = ICONPATH + "fileok.gif"
doc515 = insDoc(volume_id, gLnk("S", "ocfs2.dbg", "files/busybox/util-linux/volume_id/ocfs2.dbg"))
doc515.iconSrc = ICONPATH + "fileok.gif"
doc516 = insDoc(volume_id, gLnk("S", "reiserfs.dbg", "files/busybox/util-linux/volume_id/reiserfs.dbg"))
doc516.iconSrc = ICONPATH + "fileok.gif"
doc517 = insDoc(volume_id, gLnk("S", "romfs.dbg", "files/busybox/util-linux/volume_id/romfs.dbg"))
doc517.iconSrc = ICONPATH + "fileok.gif"
doc518 = insDoc(volume_id, gLnk("S", "sysv.dbg", "files/busybox/util-linux/volume_id/sysv.dbg"))
doc518.iconSrc = ICONPATH + "fileok.gif"
doc519 = insDoc(volume_id, gLnk("S", "udf.dbg", "files/busybox/util-linux/volume_id/udf.dbg"))
doc519.iconSrc = ICONPATH + "fileok.gif"
doc520 = insDoc(volume_id, gLnk("S", "util.dbg", "files/busybox/util-linux/volume_id/util.dbg"))
doc520.iconSrc = ICONPATH + "fileok.gif"
doc521 = insDoc(volume_id, gLnk("S", "volume_id.dbg", "files/busybox/util-linux/volume_id/volume_id.dbg"))
doc521.iconSrc = ICONPATH + "fileok.gif"
doc522 = insDoc(volume_id, gLnk("S", "xfs.dbg", "files/busybox/util-linux/volume_id/xfs.dbg"))
doc522.iconSrc = ICONPATH + "fileok.gif"
